### ISSUE TITLE
Troubles in 10.5

### ISSUE THREAD

**Issue by mercurialmusic** [elBukkit/MagicPlugin#1008]
Hey Nathan! I hope you had a good vacation.

Posted this on Discord but figured it might be easier here. Had been on Magic 10.4 with Paper-119 and experienced the same issues as everyone else. Updated today to Magic 10.5 with Paper-132 and had some weird behavior:

RP did not load automatically despite `resource_pack_default_auto: true` in the config and history of loading everything properly <10.5. `/getrp` loaded it properly. 

Everything in magic that was right-click-to-use was not working. I tested the broom, goggles, diving helmet, enchanting table (with the wand), and the wand itself (opening the inventory). No response or errors.

Spells seemed to have all gone, even our custom ones. `/cast missile`, etc. responded with unknown spell.

Looking at console it also seemed to have been unable to find my player data on join.
```
[19:28:48 WARN]: [Magic]  Failed to load player data for mercurialmusic
java.lang.ClassCastException: class org.bukkit.configuration.SectionPathData cannot be cast to class java.lang.Integer (org.bukkit.configuration.SectionPathData is in unnamed module of loader java.net.URLClassLoader @7aec35a; java.lang.Integer is in module java.base of loader 'bootstrap')
        at com.elmakers.mine.bukkit.magic.CasterProperties.getSpells(CasterProperties.java:474) ~[Magic-10.5.jar:?]
        at com.elmakers.mine.bukkit.magic.BaseMageModifier.updateSpellTriggers(BaseMageModifier.java:385) ~[Magic-10.5.jar:?]
        at com.elmakers.mine.bukkit.magic.BaseMageModifier.loadProperties(BaseMageModifier.java:362) ~[Magic-10.5.jar:?]
        at com.elmakers.mine.bukkit.magic.MageClass.load(MageClass.java:90) ~[Magic-10.5.jar:?]
        at com.elmakers.mine.bukkit.magic.Mage.load(Mage.java:1278) ~[Magic-10.5.jar:?]
        at com.elmakers.mine.bukkit.tasks.MageLoadTask.run(MageLoadTask.java:17) ~[Magic-10.5.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-132]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

To be safe I rolled back our player data to the last backup and went back to Paper-119 and Magic 10.4 without issue.
Sorry for the headaches and thanks for tackling this!

**Comment by NathanWolf** [comment]
Thank you- it looks like I missed a case, but I'm  not sure how this didn't show up in my own testing :(

**Comment by NathanWolf** [comment]
I'm hoping this is fixed in 10.5.1, but I still haven't ben able to do any extensive testing.

**Comment by mercurialmusic** [comment]
Thank you sir! Will try it out.

**Comment by mercurialmusic** [comment]
So far so good! Thanks again!

**Comment by NathanWolf** [comment]
Thank you for letting me know! Hopefully there aren't any more cases lurking in the shadows.
