### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "java.util.UUID.toString()" because "this.entityId" is null

### ISSUE THREAD

**Issue by h266579110** [elBukkit/MagicPlugin#1027]
Magic 10.6
Paper 1.18.1-216

its will happen on interactive with NPC shop (spellsshop... etc)

```
[19:46:16 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.UUID.toString()" because "this.entityId" is null
[19:46:16 WARN]:        at Magic-10.6.jar//com.elmakers.mine.bukkit.npc.MagicNPC.save(MagicNPC.java:375)
[19:46:16 WARN]:        at Magic-10.6.jar//com.elmakers.mine.bukkit.magic.MagicController.saveNPCs(MagicController.java:2922)
[19:46:16 WARN]:        at Magic-10.6.jar//com.elmakers.mine.bukkit.magic.MagicController.save(MagicController.java:3210)
[19:46:16 WARN]:        at Magic-10.6.jar//com.elmakers.mine.bukkit.tasks.AutoSaveTask.run(AutoSaveTask.java:15)
[19:46:16 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[19:46:16 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[19:46:16 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1557)
[19:46:16 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[19:46:16 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1480)
[19:46:16 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1273)
[19:46:16 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[19:46:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by NathanWolf** [comment]
This should be fixed in the current dev build, seems like your NPCs must be having issues spawning their entities though, not sure why that would be.
