### ISSUE TITLE
magic show "plugin is disable message"

### ISSUE THREAD

**Issue by mysterycb** [elBukkit/MagicPlugin#1034]
every time i try to use magic this pops up:
25.03 03:44:39 [Server] ERROR null
25.03 03:44:39 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'magic' in plugin Magic v10.6.1-92a141d - plugin is disabled.
25.03 03:44:39 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
25.03 03:44:39 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
25.03 03:44:39 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[paper-1.18.2.jar:git-Paper-267]
25.03 03:44:39 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2306) ~[?:?]
25.03 03:44:39 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2117) ~[?:?]
25.03 03:44:39 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2098) ~[?:?]
25.03 03:44:39 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
25.03 03:44:39 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
25.03 03:44:39 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
25.03 03:44:39 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-267]
25.03 03:44:39 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
25.03 03:44:39 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
25.03 03:44:39 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-267]
25.03 03:44:39 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-267]
25.03 03:44:39 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
25.03 03:44:39 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-267]
25.03 03:44:39 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-267]
25.03 03:44:39 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
25.03 03:44:39 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-267]
25.03 03:44:39 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-267]
25.03 03:44:39 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
25.03 03:44:39 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by NathanWolf** [comment]
> plugin is disabled

this means the plugin failed to load. Please give a pastebin link to your full server log, or find the part where the plugin is trying to load and fails with an error message.

Most likely you do not have the right plugin version- are you up to date/

**Comment by mysterycb** [comment]
[Magic] ModelEngine found, model magic mob configuration available
23.03 21:08:49 [Server] ERROR Error occurred while enabling Magic v10.6.1-92a141d (Is it up to date?)
23.03 21:08:49 [Server] INFO java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/MythicMobs
23.03 21:08:49 [Server] INFO at com.elmakers.mine.bukkit.integration.MythicMobManager.initialize(MythicMobManager.java:29) ~[Magic-10.6.1.jar:?]
23.03 21:08:49 [Server] INFO at com.elmakers.mine.bukkit.magic.MagicController.finalizeIntegration(MagicController.java:7916) ~[Magic-10.6.1.jar:?]
23.03 21:08:49 [Server] INFO at com.elmakers.mine.bukkit.magic.MagicController.finalizeLoad(MagicController.java:1896) ~[Magic-10.6.1.jar:?]
23.03 21:08:49 [Server] INFO at com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.run(ConfigurationLoadTask.java:991) ~[Magic-10.6.1.jar:?]
23.03 21:08:49 [Server] INFO at com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.runNow(ConfigurationLoadTask.java:1013) ~[Magic-10.6.1.jar:?]
23.03 21:08:49 [Server] INFO at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2600) ~[Magic-10.6.1.jar:?]
23.03 21:08:49 [Server] INFO at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2577) ~[Magic-10.6.1.jar:?]
23.03 21:08:49 [Server] INFO at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2573) ~[Magic-10.6.1.jar:?]
23.03 21:08:49 [Server] INFO at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2565) ~[Magic-10.6.1.jar:?]
23.03 21:08:49 [Server] INFO at com.elmakers.mine.bukkit.magic.MagicController.load(MagicController.java:2639) ~[Magic-10.6.1.jar:?]
23.03 21:08:49 [Server] INFO at com.elmakers.mine.bukkit.magic.MagicController.initialize(MagicController.java:1570) ~[Magic-10.6.1.jar:?]
23.03 21:08:49 [Server] INFO at com.elmakers.mine.bukkit.magic.MagicPlugin.initialize(MagicPlugin.java:189) ~[Magic-10.6.1.jar:?]
23.03 21:08:49 [Server] INFO at com.elmakers.mine.bukkit.magic.MagicPlugin.onEnable(MagicPlugin.java:183) ~[Magic-10.6.1.jar:?]
23.03 21:08:49 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
23.03 21:08:49 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
23.03 21:08:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
23.03 21:08:49 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-267]
23.03 21:08:49 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-267]
23.03 21:08:49 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[paper-1.18.2.jar:git-Paper-267]
23.03 21:08:49 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-267]
23.03 21:08:49 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
23.03 21:08:49 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
23.03 21:08:49 [Server] INFO Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.MythicMobs
23.03 21:08:49 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
23.03 21:08:49 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
23.03 21:08:49 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
23.03 21:08:49 [Server] INFO ... 22 more
23.03 21:08:49 [Server] INFO [Magic] Disabling Magic v10.6.1-92a141d

this is what disable it i think

**Comment by NathanWolf** [comment]
MythicMobs updated, breaking all plugins that integrate with it.

I have an experimental fix here, but no one has confirmed it's working yet:

https://jenkins.elmakers.com/job/MagicPlugin/

Alternately you can disable mythic mobs support by putting 
```
mythicmobs:
   enabled: false
```

In `plugins/Magic/config.yml`
