### ISSUE TITLE
Towny integration needs updating

### ISSUE THREAD

**Issue by purpleskier1** [elBukkit/MagicPlugin#1036]
Sometimes when casting spells I get this error and the entire server freezes for 10 seconds then TPS drops to 10 for a few minutes then goes back to normal.

[18:15:13 ERROR]: Could not pass event PlayerArmSwingEvent to Magic v10.6.1-92a141d
java.lang.NoSuchMethodError: 'com.palmergames.bukkit.towny.object.Resident com.palmergames.bukkit.towny.db.TownyDataSource.getResident(java.lang.String)'
        at com.elmakers.mine.bukkit.protection.TownyBridge.getResident(TownyBridge.java:118) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.protection.TownyBridge.getTownLocation(TownyBridge.java:133) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.protection.TownyManager.getTownLocation(TownyManager.java:95) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.magic.MagicController.getTownLocation(MagicController.java:4674) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.action.builtin.RecallAction$Waypoint.<init>(RecallAction.java:295) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.action.builtin.RecallAction.perform(RecallAction.java:673) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:43) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:221) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.action.ActionHandler.cast(ActionHandler.java:158) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.spell.ActionSpell.startCast(ActionSpell.java:172) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.spell.ActionSpell.onCast(ActionSpell.java:154) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.spell.BaseSpell.finalizeCast(BaseSpell.java:1737) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1534) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1410) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.wand.Wand.doCast(Wand.java:5368) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.wand.Wand.cast(Wand.java:5332) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.wand.Wand.cast(Wand.java:5313) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.wand.Wand.performAction(Wand.java:6817) ~[Magic-10.6.1.jar:?]
        at com.elmakers.mine.bukkit.magic.listener.PlayerController.onPlayerAnimate(PlayerController.java:704) ~[Magic-10.6.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor94.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-267]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2349) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:25) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:7) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1447) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by NathanWolf** [comment]
Looks like either Towny updated and broke their API, or you have an outdated Towny.

Either way you can probably work around it by turning off the Magic/Towny integration

```
/mconfig config towny_enabled false
```

**Comment by purpleskier1** [comment]
Thank you for the quick response. My Towny is up to date so I guess they updated the API. If I turn off the Towny/Magic integration is that going to cause issues with Magic that you know of like causing permanent damage? Otherwise I guess I will just need to live with it until everything is up to date again.

**Comment by NathanWolf** [comment]
It will mean players can use destructive spells in towns, and the pvp restrictions won't work. It's not great.

World changes will still undo as normal.

If necessary you can do `/mexample add safe` for now, this will turn off all destructive magic.
