### ISSUE TITLE
blast spell error

### ISSUE THREAD

**Issue by 0MrCrazy0** [elBukkit/MagicPlugin#1038]
[19:30:26 WARN]: [Magic]  Trying to add to a finished UndoList, this may result in blocks that don't get cleaned up: Blast
[19:30:26 WARN]: java.lang.Exception: Stack trace
[19:30:26 WARN]:        at java.base/java.lang.Thread.dumpStack(Thread.java:1380)
[19:30:26 WARN]:        at Magic-10.7-SNAPSHOT.jar//com.elmakers.mine.bukkit.block.UndoList.add(UndoList.java:246)
[19:30:26 WARN]:        at Magic-10.7-SNAPSHOT.jar//com.elmakers.mine.bukkit.block.BlockList.add(BlockList.java:51)
[19:30:26 WARN]:        at Magic-10.7-SNAPSHOT.jar//com.elmakers.mine.bukkit.magic.listener.BlockController.onBlockFade(BlockController.java:243)
[19:30:26 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor98.execute(Unknown Source)
[19:30:26 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[19:30:26 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[19:30:26 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:30:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
[19:30:26 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callBlockFadeEvent(CraftEventFactory.java:824)
[19:30:26 WARN]:        at net.minecraft.world.level.block.BlockDirtSnowSpreadable.b(BlockDirtSnowSpreadable.java:46)
[19:30:26 WARN]:        at net.minecraft.world.level.block.state.BlockBase$BlockData.b(BlockBase.java:999)
[19:30:26 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:838)
[19:30:26 WARN]:        at net.minecraft.server.level.ChunkProviderServer.r(ChunkProviderServer.java:1035)
[19:30:26 WARN]:        at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:915)
[19:30:26 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:628)
[19:30:26 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1591)
[19:30:26 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)
[19:30:26 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1455)
[19:30:26 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1225)
[19:30:26 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[19:30:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by NathanWolf** [comment]
Sorry for never responding- was this a one-off or is it repeatable?
