### ISSUE TITLE
Issue when using /magic reload

### ISSUE THREAD

**Issue by Naghell** [elBukkit/MagicPlugin#1058]
Hi, what happens is, when using /magic reload, the plugin makes a false reload. It takes about 2 minutes to reload from that WARN, and at the end it doesn't reload.

```
[22:23:56 INFO]: Naghell issued server command: /magic reload
[22:23:56 INFO]: [Magic]  Using compatibility configs: examples/versions/1.16/config.yml
[22:23:56 INFO]: [Magic]  Using compatibility configs: examples/versions/1.16/config.yml
[22:23:56 INFO]: [Magic]  Using compatibility configs: examples/versions/1.16/messages.yml
[22:23:56 INFO]: [Magic] Note: You have a messages at /home/container/plugins/Magic/messages/base.yml that was copied from the defaults, will ignore anything that is set to the same as defaults to avoid unintentionally overriding loaded examples
[22:23:56 INFO]: [Magic]  Using compatibility configs: examples/versions/1.16/spells.yml
[22:23:56 INFO]: [Magic]  Using compatibility configs: examples/versions/1.16/wands.yml
[22:23:56 INFO]: [Magic]  Using compatibility configs: examples/versions/1.16/items.yml
[22:23:56 INFO]: [Magic]  Using compatibility configs: examples/versions/1.16/crafting.yml
[22:23:56 INFO]: [Magic]  Using compatibility configs: examples/versions/1.16/mobs.yml
[22:23:56 INFO]: [Magic] Loaded 0 attributes
[22:23:56 INFO]: [Magic] Skin-based spell icons enabled
[22:23:56 WARN]: [Magic] Task #227864 for Magic v10.7.1-3a90ae4 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
        at com.elmakers.mine.bukkit.utility.platform.base.CompatibilityUtilsBase.getEnchantmentBaseKey(CompatibilityUtilsBase.java:816) ~[?:?]
        at com.elmakers.mine.bukkit.utility.platform.base.CompatibilityUtilsBase.getEnchantmentBaseKeys(CompatibilityUtilsBase.java:828) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.finalizeAttributes(MagicController.java:3613) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.processConfigurations(MagicController.java:2059) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.finalizeLoad(MagicController.java:1887) ~[?:?]
        at com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask$1.run(ConfigurationLoadTask.java:998) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1432) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-790]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by NathanWolf** [comment]
Do you have some weird enchantment plugin? You've got an enchantment with an empty key, which I think shouldn't happen.

I put a work-around in but can't test it. You can try this dev build if you want:

https://jenkins.elmakers.com/job/MagicPlugin/4169/
