### ISSUE TITLE
Error loading fonts in Tag spell

### ISSUE THREAD

**Issue by alekso56** [elBukkit/MagicPlugin#1060]
```
 [Craft Scheduler Thread - 41041 - Magic/WARN]: [Magic] Plugin Magic v10.7.1-3a90ae4 generated an exception while executing task 156567596
java.lang.InternalError: java.lang.reflect.InvocationTargetException
        at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:87) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
        at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:75) ~[?:?]
        at sun.font.SunFontManager.getInstance(SunFontManager.java:248) ~[?:?]
        at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:266) ~[?:?]
        at sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:863) ~[?:?]
        at com.elmakers.mine.bukkit.slikey.effectlib.util.StringParser.stringToBufferedImage(StringParser.java:29) ~[Magic-10.7.1.jar:?]
        at com.elmakers.mine.bukkit.slikey.effectlib.effect.TextEffect.onRun(TextEffect.java:103) ~[Magic-10.7.1.jar:?]
        at com.elmakers.mine.bukkit.slikey.effectlib.Effect.run(Effect.java:299) ~[Magic-10.7.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-347]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-347]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-347]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedConstructorAccessor796.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:85) ~[?:?]
        ... 14 more
```

**Comment by NathanWolf** [comment]
Seems like an issue loading fonts, not sure why.

The only spell that uses the text effect in the builtin configs is tag, so you may want to just disable that one

`/mconfig disable spell tag`
