### ISSUE TITLE
Not compatible with 1.19.2

### ISSUE THREAD

**Issue by zopn333** [elBukkit/MagicPlugin#1098]
Magic plugin loaded, but have compatible issues:
`[10:38:02] [Server thread/ERROR]: [Magic] [31m Failed to load compatibility layer, the plugin may need to be updated to work with your server version[0m
java.lang.ClassNotFoundException: com.elmakers.mine.bukkit.utility.platform.v1_19_2.Platform
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at com.elmakers.mine.bukkit.utility.CompatibilityLib.initialize(CompatibilityLib.java:53) ~[Magic-10.8.2.jar:?]
	at com.elmakers.mine.bukkit.magic.MagicController.registerNMSBindings(MagicController.java:690) ~[Magic-10.8.2.jar:?]
	at com.elmakers.mine.bukkit.magic.MagicPlugin.onLoad(MagicPlugin.java:164) ~[Magic-10.8.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:427) ~[paper-1.19.2.jar:git-Paper-113]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.2.jar:git-Paper-113]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.2.jar:git-Paper-113]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-113]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

**Comment by NathanWolf** [comment]
Jeez, there’s a 1.19.2 already? I’ll get an update released as soon as I can, but it may take some time.

**Comment by NathanWolf** [comment]
Added 1.19.2 support in this dev build: https://jenkins.elmakers.com/job/MagicPlugin/4192/

Untested, please let me know if it works :joy:

**Comment by zopn333** [comment]
Installed, works fine for now. I will report here if meet any bugs.

**Comment by U-R-E** [comment]
> Added 1.19.2 support in this dev build: https://jenkins.elmakers.com/job/MagicPlugin/4192/
> 
> Untested, please let me know if it works 😂

It's working great so far, I will keep an eye out for any bugs as well. Thank you for the fast update.
