### ISSUE TITLE
Arrow spell throws error, no cooldown/cost taken

### ISSUE THREAD

**Issue by adamk523** [elBukkit/MagicPlugin#1111]
Getting the below error in console when casting the Arrow spell. When casting, it throws the arrow as expected, but the arrow can be picked up, and it does not subtract the cost from mana, etc. It also does not account for the cooldown, so you can spam as many arrows as you want to. This might be an issue with other spells that use the PlayerArmSwingEvent (Magic Missile does not have this error for example).
Server: latest Purpur 1.18.2 build

`[ERROR]: Could not pass event PlayerArmSwingEvent to Magic v10.8.2-4a2e3b4
java.lang.NoSuchFieldError: au
        at com.elmakers.mine.bukkit.utility.platform.v1_18_2.CompatibilityUtils.decreaseLifespan(CompatibilityUtils.java:838) ~[Magic-10.8.2.jar:?]
        at com.elmakers.mine.bukkit.action.builtin.ProjectileAction.start(ProjectileAction.java:185) ~[Magic-10.8.2.jar:?]
        at com.elmakers.mine.bukkit.action.CompoundAction.perform(CompoundAction.java:94) ~[Magic-10.8.2.jar:?]
        at com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:43) ~[Magic-10.8.2.jar:?]
        at com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:221) ~[Magic-10.8.2.jar:?]
        at com.elmakers.mine.bukkit.action.ActionHandler.cast(ActionHandler.java:158) ~[Magic-10.8.2.jar:?]
        at com.elmakers.mine.bukkit.spell.ActionSpell.startCast(ActionSpell.java:172) ~[Magic-10.8.2.jar:?]
        at com.elmakers.mine.bukkit.spell.ActionSpell.onCast(ActionSpell.java:154) ~[Magic-10.8.2.jar:?]
        at com.elmakers.mine.bukkit.spell.BaseSpell.finalizeCast(BaseSpell.java:1767) ~[Magic-10.8.2.jar:?]
        at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1564) ~[Magic-10.8.2.jar:?]
        at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1440) ~[Magic-10.8.2.jar:?]
        at com.elmakers.mine.bukkit.wand.Wand.doCast(Wand.java:5400) ~[Magic-10.8.2.jar:?]
        at com.elmakers.mine.bukkit.wand.Wand.cast(Wand.java:5364) ~[Magic-10.8.2.jar:?]
        at com.elmakers.mine.bukkit.wand.Wand.cast(Wand.java:5345) ~[Magic-10.8.2.jar:?]
        at com.elmakers.mine.bukkit.wand.Wand.performAction(Wand.java:6862) ~[Magic-10.8.2.jar:?]
        at com.elmakers.mine.bukkit.magic.listener.PlayerController.onPlayerAnimate(PlayerController.java:713) ~[Magic-10.8.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor78.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2433) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:25) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.a(ServerboundSwingPacket.java:11) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1257) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by NathanWolf** [comment]
... That said, I think this particular error has a workaround in current releases of Magic, if you want to try updating.
