### ISSUE TITLE
Error ConfigurationSerialization, java.lang.IllegalArgumentException: Material cannot be null

### ISSUE THREAD

**Issue by ondrejlohnisky** [elBukkit/MagicPlugin#1122]
I am having errors about serialization:
Any suggestions?
`[05:38:46] [Server thread/INFO]: [Magic] Enabling Magic v10.8.3-5a21fa4
[05:38:46] [Server thread/INFO]: [Magic] EffectLib initialized
[05:38:46] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.IllegalArgumentException: Material cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:85) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:73) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:515) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:48) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:235) ~[snakeyaml-1.32.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:224) ~[snakeyaml-1.32.jar:?]
	at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:27) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:159) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:157) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:116) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at com.elmakers.mine.bukkit.utility.platform.base.CompatibilityUtilsBase.loadConfiguration(CompatibilityUtilsBase.java:256) ~[Magic-10.8.3.jar:?]
	at com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.loadConfiguration(ConfigurationLoadTask.java:458) ~[Magic-10.8.3.jar:?]
	at com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.loadConfigFolder(ConfigurationLoadTask.java:786) ~[Magic-10.8.3.jar:?]
	at com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.loadConfigFile(ConfigurationLoadTask.java:597) ~[Magic-10.8.3.jar:?]
	at com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.run(ConfigurationLoadTask.java:967) ~[Magic-10.8.3.jar:?]
	at com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.runNow(ConfigurationLoadTask.java:1013) ~[Magic-10.8.3.jar:?]
	at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2602) ~[Magic-10.8.3.jar:?]
	at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2579) ~[Magic-10.8.3.jar:?]
	at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2575) ~[Magic-10.8.3.jar:?]
	at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2567) ~[Magic-10.8.3.jar:?]
	at com.elmakers.mine.bukkit.magic.MagicController.load(MagicController.java:2641) ~[Magic-10.8.3.jar:?]
	at com.elmakers.mine.bukkit.magic.MagicController.initialize(MagicController.java:1568) ~[Magic-10.8.3.jar:?]
	at com.elmakers.mine.bukkit.magic.MagicPlugin.initialize(MagicPlugin.java:190) ~[Magic-10.8.3.jar:?]
	at com.elmakers.mine.bukkit.magic.MagicPlugin.onEnable(MagicPlugin.java:184) ~[Magic-10.8.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-171]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-171]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.2.jar:git-Paper-171]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-171]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-171]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by NathanWolf** [comment]
Sorry I didn't respond to you! This looked like some kind of invalid saved item but I wasn't sure- did you figure it out?
