### ISSUE TITLE
java.lang.IllegalStateException: Circular plugin dependencies from plugins Magic

### ISSUE THREAD

**Issue by padakoys** [elBukkit/MagicPlugin#1177]
[20:15:36] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Circular plugin dependencies from plugins Magic, Magic
	at io.papermc.paper.plugin.storage.ConfiguredProviderStorage.handleCycle(ConfiguredProviderStorage.java:43) ~[paper-1.19.3.jar:git-Paper-408]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:34) ~[paper-1.19.3.jar:git-Paper-408]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:37) ~[paper-1.19.3.jar:git-Paper-408]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:429) ~[paper-1.19.3.jar:git-Paper-408]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.3.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-408]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	
	
	
This error comes only if I use the 1.19.3-408 build of paper.

**Comment by NathanWolf** [comment]
This is fixed already in the latest dev build, I will be making a release as soon as I can.

**Comment by padakoys** [comment]
Well, I work with docker and it smashes my nerves because the image doesn't allow me to add a specific build. So, I will wait till the next stable build of paper I guess
