### ISSUE TITLE
Issue loading Java font manager

### ISSUE THREAD

**Issue by Arthuuurr** [elBukkit/MagicPlugin#1192]
Hello!
Today I put the magic plugin in my server, but it gives me several things error.
Can they fix the problem? Thank you!

https://paste.iruvatar.com/hupaqekepi.apache

**Comment by NathanWolf** [comment]
What server software are you running?

Are you able to check what JVM (java --version) you have?

Not sure I can do anything about standard java libraries failing to load :(

**Comment by Arthuuurr** [comment]
I'm ussing paper 1.19.2

Java 17

I don't understand why it gives me that error, I took out X item (I don't remember its name) and it started giving an error.

**Comment by NathanWolf** [comment]
```
10.03 18:01:49 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class sun.font.SunFontManager
10.03 18:01:49 [Server] INFO at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:266) ~[?:?]
10.03 18:01:49 [Server] INFO at sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:863) ~[?:?]
10.03 18:01:49 [Server] INFO at com.elmakers.mine.bukkit.slikey.effectlib.util.StringParser.stringToBufferedImage(StringParser.java:29) ~[Magic-10.8.6.jar:?]
10.03 18:01:49 [Server] INFO at com.elmakers.mine.bukkit.slikey.effectlib.effect.TextEffect.onRun(TextEffect.java:103) ~[Magic-10.8.6.jar:?]
10.03 18:01:49 [Server] INFO at com.elmakers.mine.bukkit.slikey.effectlib.Effect.run(Effect.java:299) ~[Magic-10.8.6.jar:?]
10.03 18:01:49 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
10.03 18:01:49 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-307]
10.03 18:01:49 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
10.03 18:01:49 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
10.03 18:01:49 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
10.03 18:01:49 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by NathanWolf** [comment]
You might try disabling the tag spell, that's the only thing I can think of in the builtin configs that uses the TextEffect, which is likely the culprit here.

`/mconfig disable spell tag`

**Comment by Arthuuurr** [comment]
should be fixed by putting this command?

**Comment by NathanWolf** [comment]
Try it and see.
