### ISSUE TITLE
MC 1.21.1 - paper 81 - NoSuchMethodException: CraftMetaSkull.setProfile

### ISSUE THREAD

**Issue by alekso56** [elBukkit/MagicPlugin#1376]
```
[Server thread/ERROR]: [Magic]  Error calling private method of org.bukkit.craftbukkit.inventory.CraftMetaSkull.setProfile
java.lang.NoSuchMethodException: org.bukkit.craftbukkit.inventory.CraftMetaSkull.setProfile(com.mojang.authlib.GameProfile)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2848) ~[?:?]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredMethod(AbstractDefaultRulesReflectionProxy.java:95) ~[reflection-rewriter-runtime-0.0.3.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredMethod(Unknown Source) ~[paper-1.21.1.jar:1.21.1-81-13a2395]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.ReflectionUtils.callPrivate(ReflectionUtils.java:87) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.platform.v1_21_1.InventoryUtils.setSkullProfile(InventoryUtils.java:326) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.platform.v1_21_1.InventoryUtils.setSkullURL(InventoryUtils.java:293) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.platform.base.InventoryUtilsBase.setSkullURL(InventoryUtilsBase.java:210) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.platform.base.InventoryUtilsBase.setSkullURL(InventoryUtilsBase.java:199) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.block.MaterialAndData.update(MaterialAndData.java:336) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.block.MaterialAndData.<init>(MaterialAndData.java:194) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.ConfigurationUtils.toMaterialAndData(ConfigurationUtils.java:87) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.ConfigurationUtils.getMaterialAndData(ConfigurationUtils.java:64) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.ConfigurationUtils.getMaterialAndData(ConfigurationUtils.java:54) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.economy.BaseMagicCurrency.<init>(BaseMagicCurrency.java:43) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.economy.BaseMagicCurrency.<init>(BaseMagicCurrency.java:32) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.economy.ManaCurrency.<init>(ManaCurrency.java:11) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.registerHandlers(MagicController.java:3545) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.finalizeLoad(MagicController.java:1890) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.run(ConfigurationLoadTask.java:991) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.runNow(ConfigurationLoadTask.java:1013) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2606) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2583) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2579) ~[Magic-10.9.3.jar:?]
```

**Comment by archmagesmith** [comment]
[latest.log](https://github.com/user-attachments/files/17177850/latest.log)

Hi all! It seems that I'm also receiving this error in my console and logs, so I just thought I'd bump this issue. I noticed that OP recommended changing some parameters but I gave up on trying to compile a .jar file after 8 hours of severely beginner-level errors (I made progress after jumping ship from IntelliJ to PowerShell but finally gave up when Maven kept failing from missing dependencies (EffectLib; Citizens; Maxlego08's AuctionHouse) - it seems coding isn't for me!

Apologies if I'm missing anything or if this is already being solved, I'm unsure about the etiquette on GitHub. I've attached the .log file from a server containing only the Magic plugin, and copied in the relevant errors below. 

_The error repeats as below, with com.elmakers.mine.bukkit.economy.ManaCurrency, ...VaultCurrency, ...CustomCurrency, ...LevelCurrency, HungerCurrency, HealthCurrency, and ExperienceCurrency at roughly the same place_

```[05:32:46] [Server thread/ERROR]: [Magic]  Error calling private method of org.bukkit.craftbukkit.inventory.CraftMetaSkull.setProfile
java.lang.NoSuchMethodException: org.bukkit.craftbukkit.inventory.CraftMetaSkull.setProfile(com.mojang.authlib.GameProfile)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2848) ~[?:?]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredMethod(AbstractDefaultRulesReflectionProxy.java:95) ~[reflection-rewriter-runtime-0.0.3.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredMethod(Unknown Source) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.ReflectionUtils.callPrivate(ReflectionUtils.java:87) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.platform.v1_21_1.InventoryUtils.setSkullProfile(InventoryUtils.java:326) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.platform.v1_21_1.InventoryUtils.setSkullURL(InventoryUtils.java:293) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.platform.base.InventoryUtilsBase.setSkullURL(InventoryUtilsBase.java:210) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.platform.base.InventoryUtilsBase.setSkullURL(InventoryUtilsBase.java:199) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.block.MaterialAndData.update(MaterialAndData.java:336) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.block.MaterialAndData.<init>(MaterialAndData.java:194) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.ConfigurationUtils.toMaterialAndData(ConfigurationUtils.java:87) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.ConfigurationUtils.getMaterialAndData(ConfigurationUtils.java:64) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.ConfigurationUtils.getMaterialAndData(ConfigurationUtils.java:54) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.economy.BaseMagicCurrency.<init>(BaseMagicCurrency.java:43) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.economy.BaseMagicCurrency.<init>(BaseMagicCurrency.java:32) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.economy.ManaCurrency.<init>(ManaCurrency.java:11) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.registerHandlers(MagicController.java:3545) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.finalizeLoad(MagicController.java:1890) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.run(ConfigurationLoadTask.java:991) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.runNow(ConfigurationLoadTask.java:1013) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2606) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2583) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2579) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2571) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.load(MagicController.java:2645) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.initialize(MagicController.java:1572) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicPlugin.initialize(MagicPlugin.java:190) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicPlugin.onEnable(MagicPlugin.java:184) ~[Magic-10.9.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:293) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

_After that is this error, below, which alternates between getItemMaterial(Icon.java:157) & getItemMaterial(Icon.java:135) or getItemDisabledMaterial(Icon.java:196) & getItemDisabledMaterial(Icon.java:171). This repeats an uncountable number of times in the span of 3 seconds._

```[05:32:49] [Server thread/ERROR]: [Magic]  Error calling private method of org.bukkit.craftbukkit.inventory.CraftMetaSkull.setProfile
java.lang.NoSuchMethodException: org.bukkit.craftbukkit.inventory.CraftMetaSkull.setProfile(com.mojang.authlib.GameProfile)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2848) ~[?:?]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredMethod(AbstractDefaultRulesReflectionProxy.java:95) ~[reflection-rewriter-runtime-0.0.3.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredMethod(Unknown Source) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.ReflectionUtils.callPrivate(ReflectionUtils.java:87) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.platform.v1_21_1.InventoryUtils.setSkullProfile(InventoryUtils.java:326) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.platform.v1_21_1.InventoryUtils.setSkullURL(InventoryUtils.java:293) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.platform.base.InventoryUtilsBase.setSkullURL(InventoryUtilsBase.java:210) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.platform.base.InventoryUtilsBase.setSkullURL(InventoryUtilsBase.java:199) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.block.MaterialAndData.update(MaterialAndData.java:336) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.block.MaterialAndData.<init>(MaterialAndData.java:194) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.getGenericItemStack(MagicController.java:6009) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.createItem(MagicController.java:5912) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.createItem(MagicController.java:5699) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.item.ItemData.getOrCreateItemStack(ItemData.java:381) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.item.ItemData.getMaterialAndData(ItemData.java:445) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.item.ItemData.getMaterialAndData(ItemData.java:30) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.item.Icon.getItem(Icon.java:124) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.item.Icon.getItemMaterial(Icon.java:157) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.item.Icon.getItemMaterial(Icon.java:135) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.spell.BaseSpell.loadTemplate(BaseSpell.java:1089) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.spell.UndoableSpell.loadTemplate(UndoableSpell.java:68) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.spell.BrushSpell.loadTemplate(BrushSpell.java:112) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.spell.ActionSpell.loadTemplate(ActionSpell.java:207) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.spell.BaseSpell.loadTemplate(BaseSpell.java:957) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.spell.BaseSpell.loadTemplate(BaseSpell.java:948) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.loadSpell(MagicController.java:685) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.loadSpells(MagicController.java:5222) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.finalizePostStartupLoad(MagicController.java:1962) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.tasks.PostStartupLoadTask.run(PostStartupLoadTask.java:20) ~[Magic-10.9.3.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

_I have also copied in some errors from my main server, which contains other plugins. These errors would repeat through the entire runtime of the server, creating relatively large .log files. We have the typical error from the CraftMetaSkull code:_

```[23:34:23] [Server thread/ERROR]: [Magic]  Error calling private method of org.bukkit.craftbukkit.inventory.CraftMetaSkull.setProfile
java.lang.NoSuchMethodException: org.bukkit.craftbukkit.inventory.CraftMetaSkull.setProfile(com.mojang.authlib.GameProfile)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2848) ~[?:?]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredMethod(AbstractDefaultRulesReflectionProxy.java:95) ~[reflection-rewriter-runtime-0.0.3.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredMethod(Unknown Source) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.ReflectionUtils.callPrivate(ReflectionUtils.java:87) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.platform.v1_21_1.InventoryUtils.setSkullProfile(InventoryUtils.java:326) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.platform.v1_21_1.InventoryUtils.setSkullURL(InventoryUtils.java:293) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.platform.base.InventoryUtilsBase.setSkullURL(InventoryUtilsBase.java:210) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.utility.platform.base.InventoryUtilsBase.setSkullURL(InventoryUtilsBase.java:199) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.block.MaterialAndData.update(MaterialAndData.java:336) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.block.MaterialAndData.<init>(MaterialAndData.java:194) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.getGenericItemStack(MagicController.java:6009) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.createItem(MagicController.java:5912) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.MagicController.createItem(MagicController.java:5699) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.item.ItemData.getOrCreateItemStack(ItemData.java:381) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.item.ItemData.getMaterialAndData(ItemData.java:445) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.item.ItemData.getMaterialAndData(ItemData.java:30) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.item.Icon.getItem(Icon.java:124) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.item.Icon.getItemDisabledMaterial(Icon.java:196) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.item.Icon.getItemDisabledMaterial(Icon.java:171) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.spell.BaseSpell.loadTemplate(BaseSpell.java:1090) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.spell.UndoableSpell.loadTemplate(UndoableSpell.java:68) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.spell.BrushSpell.loadTemplate(BrushSpell.java:112) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.spell.ActionSpell.loadTemplate(ActionSpell.java:207) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.spell.BaseSpell.loadTemplate(BaseSpell.java:957) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.spell.BaseSpell.loadTemplate(BaseSpell.java:948) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.spell.BaseSpell.createMageSpell(BaseSpell.java:2354) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.Mage.createSpell(Mage.java:2433) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.Mage.getSpell(Mage.java:2408) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.wand.Wand.buildInventory(Wand.java:1436) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.wand.Wand.activate(Wand.java:5917) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.wand.Wand.activate(Wand.java:5751) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.Mage.checkMainhandWand(Mage.java:1732) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.magic.Mage.checkWand(Mage.java:1747) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.tasks.CheckWandTask.run(CheckWandTask.java:21) ~[Magic-10.9.3.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

_But there also seems to be another error concerning EffectLib, constantly repeating and filling up the console. I'm unsure if this error is connected._

```[23:26:26] [Craft Scheduler Thread - 2480 - Magic/ERROR]: [Magic]  Unexpected EffectLib Error: missing required data class org.bukkit.Color
java.lang.IllegalArgumentException: missing required data class org.bukkit.Color
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:68) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2993) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2983) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
	at org.bukkit.craftbukkit.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2978) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.slikey.effectlib.util.ParticleDisplay.spawnParticle(ParticleDisplay.java:37) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.slikey.effectlib.util.versions.ParticleDisplay_20_5.display(ParticleDisplay_20_5.java:80) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.slikey.effectlib.EffectManager.display(EffectManager.java:90) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.slikey.effectlib.Effect.display(Effect.java:769) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.slikey.effectlib.Effect.display(Effect.java:750) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.slikey.effectlib.Effect.display(Effect.java:742) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.slikey.effectlib.Effect.display(Effect.java:738) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.slikey.effectlib.effect.AnimatedBallEffect.onRun(AnimatedBallEffect.java:96) ~[Magic-10.9.3.jar:?]
	at Magic-10.9.3.jar/com.elmakers.mine.bukkit.slikey.effectlib.Effect.run(Effect.java:659) ~[Magic-10.9.3.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.1.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

I hope this .log is helpful! I can't fathom how exhausting working on this wonderful plugin must be, especially with the jump to 1.21. I understand that development will continue to slow down, but it's been great having what already exists of the plugin. Thank you so much for all the work you do, NathanWolf.

**Comment by alekso56** [comment]
> compile a .jar file after 8 hours of severely beginner-level errors 

Feel free to use my compiled version.
you have to compile effectlib first to get magic to compile.

(extract from zip)
[Magic-10.9.4-SNAPSHOT.zip](https://github.com/user-attachments/files/17181160/Magic-10.9.4-SNAPSHOT.zip)

**Comment by archmagesmith** [comment]
> Feel free to use my compiled version. you have to compile effectlib first to get magic to compile.

Ah, that must have been it. Thank you very, very much for this!

**Comment by NathanWolf** [comment]
Thank you for the fix!
Sorry I didn't get to fixing this myself. I didn't realize it was only a problem in newer versions of 1.21.1, and I hadn't updated my test server in a good while.
