### ISSUE TITLE
Flying broomstick into Nether Portal crashes the server

### ISSUE THREAD

**Issue by swim709** [elBukkit/MagicPlugin#1396]
Paper 1.21.1 server, running Magic-10.9.5-SNAPSHOT.

Every time a player fly's their broomstick directly into a Nether Portal, the server shuts down.

```
[20:54:40] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Ticking retired scheduler
    at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:147) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
    at net.minecraft.server.MinecraftServer.lambda$tickChildren$20(MinecraftServer.java:1735) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
    at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:833) ~[?:?]
    at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116) ~[?:?]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1728) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
    at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:54:40] [Server thread/ERROR]: This crash report has been saved to: /home/amp/.ampdata/instances/ElationStation01/Minecraft/crash-reports/crash-2024-11-20_20.54.40-server.txt
[20:54:40] [Server thread/INFO]: Stopping server
```

[crash-2024-11-20_20.54.40-server(1).txt](https://github.com/user-attachments/files/17924257/crash-2024-11-20_20.54.40-server.1.txt)

**Comment by NathanWolf** [comment]
Yuck :(

I was able to reproduce this, I'll see what I can do.  I don't have any idea what "Ticking retired scheduler" means ... I'll maybe just force-dismount players when they enter a portal.

It's interesting that it happens immediately upon touching the portal, not after waiting for the teleport. Very strange.

**Comment by NathanWolf** [comment]
The crash is fixed in this dev build:

https://jenkins.elmakers.com/job/MagicPlugin/4313/

On a related note, I am aware that broom controls aren't working in 1.20.3 ... I looked into it a bit and unfortunately it seems like the method I had been using to detect WASD/space controls is no longer working. I'm not sure what i can do about that.

**Comment by swim709** [comment]
Thanks!
