### ISSUE TITLE
Commands didnt work

### ISSUE THREAD

**Issue by samsung22** [elBukkit/MagicPlugin#15]
Hey so i installed the magic plugin and when i typed in any of the commands it just kept bring up the same list of commands could someone please tell me what im doing wrong

**Comment by NathanWolf** [comment]
Please check your server logs when your server starts up. There is probably an error in there, most likely to be a server/plugin compatibility issue. If in doubt, paste your logs into http://www.pastebin.com and paste the link here.

**Comment by samsung22** [comment]
http://pastebin.com/X7g1Figy
And the plugins I have are 
commandbook
craftbook
deathchest
factions
headslite
magic
massive core
multiverse core
multiverse portals 
mythicmobs

**Comment by NathanWolf** [comment]
The most recent version of Magic require Spigot 1.8.8. You'll need to go back to Magic 5.4 or update your server.

```
[11:44:35] [Server thread/INFO]: [Magic] Enabling Magic v5.4.5
[11:44:35] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_8_R1.EntityArmorStand.n(boolean)
[11:44:35] [Server thread/WARN]:    at java.lang.Class.getDeclaredMethod(Class.java:2130)
[11:44:35] [Server thread/WARN]:    at com.elmakers.mine.bukkit.utility.NMSUtils.<clinit>(NMSUtils.java:351)
[11:44:35] [Server thread/WARN]:    at com.elmakers.mine.bukkit.magic.MagicPlugin.onEnable(MagicPlugin.java:155)
[11:44:35] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[11:44:35] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[11:44:35] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[11:44:35] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
[11:44:35] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
[11:44:35] [Server thread/WARN]:    at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
[11:44:35] [Server thread/WARN]:    at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
[11:44:35] [Server thread/WARN]:    at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
[11:44:35] [Server thread/WARN]:    at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
[11:44:35] [Server thread/WARN]:    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505)
[11:44:35] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[11:44:35] [Server thread/WARN]: [Magic] Something went wrong with some Deep Magic, plugin will not load.
[11:44:35] [Server thread/WARN]: [Magic] Please make sure you are running a compatible version of CraftBukkit or Spigot!
```
