### ISSUE TITLE
/wand enchant throwing error

### ISSUE THREAD

**Issue by Volkenstein666** [elBukkit/MagicPlugin#164]
while holding a stick...

`[13:24:44 INFO]: Volkenstein13 issued server command: /wand enchant
[13:24:44 WARN]: java.lang.IllegalArgumentException: Item stack must be a wand
[13:24:44 WARN]:        at com.google.common.base.Preconditions.checkArgument(Pr
econditions.java:125)
[13:24:44 WARN]:        at com.elmakers.mine.bukkit.magic.MagicController.getWan
d(MagicController.java:3473)
[13:24:44 WARN]:        at com.elmakers.mine.bukkit.wand.Wand.createWand(Wand.ja
va:2760)
[13:24:44 WARN]:        at com.elmakers.mine.bukkit.magic.MagicPlugin.createWand
(MagicPlugin.java:497)
[13:24:44 WARN]:        at com.elmakers.mine.bukkit.magic.command.WandCommandExe
cutor.onWandEnchant(WandCommandExecutor.java:683)
[13:24:44 WARN]:        at com.elmakers.mine.bukkit.magic.command.WandCommandExe
cutor.processWandCommand(WandCommandExecutor.java:363)
[13:24:44 WARN]:        at com.elmakers.mine.bukkit.magic.command.WandCommandExe
cutor.onCommand(WandCommandExecutor.java:102)
[13:24:44 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
[13:24:44 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:141)
[13:24:44 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchC
ommand(CraftServer.java:647)
[13:24:44 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.handle
Command(PlayerConnection.java:1358)
[13:24:44 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.a(Play
erConnection.java:1193)
[13:24:44 WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(Pack
etPlayInChat.java:45)
[13:24:44 WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(Pack
etPlayInChat.java:1)
[13:24:44 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1
.run(SourceFile:13)
[13:24:44 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[13:24:44 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[13:24:44 WARN]:        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFil
e:45)
[13:24:44 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(Minec
raftServer.java:732)
[13:24:44 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(Dedic
atedServer.java:400)
[13:24:44 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(Minec
raftServer.java:668)
[13:24:44 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(Min
ecraftServer.java:567)
[13:24:44 WARN]:        at java.lang.Thread.run(Unknown Source)
[13:24:44 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'wand
' in plugin Magic v6.2.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[cus
tom.jar:git-Spigot-72c2605-709783c]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) ~[custom.jar:git-Spigot-72c2605-709783c]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServ
er.java:647) ~[custom.jar:git-Spigot-72c2605-709783c]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerCo
nnection.java:1358) [custom.jar:git-Spigot-72c2605-709783c]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.jav
a:1193) [custom.jar:git-Spigot-72c2605-709783c]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.jav
a:45) [custom.jar:git-Spigot-72c2605-709783c]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.jav
a:1) [custom.jar:git-Spigot-72c2605-709783c]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:
13) [custom.jar:git-Spigot-72c2605-709783c]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [custom.ja
r:git-Spigot-72c2605-709783c]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:
732) [custom.jar:git-Spigot-72c2605-709783c]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:
400) [custom.jar:git-Spigot-72c2605-709783c]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:
668) [custom.jar:git-Spigot-72c2605-709783c]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.jav
a:567) [custom.jar:git-Spigot-72c2605-709783c]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at com.elmakers.mine.bukkit.magic.command.WandCommandExecutor.onWandEnch
ant(WandCommandExecutor.java:684) ~[?:?]
        at com.elmakers.mine.bukkit.magic.command.WandCommandExecutor.processWan
dCommand(WandCommandExecutor.java:363) ~[?:?]
        at com.elmakers.mine.bukkit.magic.command.WandCommandExecutor.onCommand(
WandCommandExecutor.java:102) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[cus
tom.jar:git-Spigot-72c2605-709783c]
        ... 15 more`

I am using the latest magic version(6.2.4) and the latest spigot version as of today - 11/8/16
as a side note - I get the error message 'you are not allowed to use that command' when I do /magic help

usually this plugin runs flawlessly

**Comment by NathanWolf** [comment]
Sorry, looks like the enchant command got broken. It's fixed in the latest dev build:

http://jenkins.elmakers.com/job/MagicPlugin/1750/com.elmakers.mine.bukkit.plugins$Magic/

Magic has no help command, it just uses Spigot's built-in help system. Try "/help Magic", "/help wand", etc.

**Comment by Volkenstein666** [comment]
thank you for the quick reply- your plugin is great and so is the customer service
