### ISSUE TITLE
Can't spawn magic mobs based on villagers

### ISSUE THREAD

**Issue by sargunster** [elBukkit/MagicPlugin#172]
I try to spawn the `dark_wizard` from the default config: `/mmob spawn dark_wizard`, and the plugin throws an UnsupportedOperationException. Spawning non-villager ones such as the `dark_spider` works fine.

Using latest dev build of the plugin with latest 1.11 build of SpigotMC.

```
[05:51:31 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mmob' in plugin Magic v6.4-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-f950f8e-0a81101]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-f950f8e-0a81101]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[server.jar:git-Spigot-f950f8e-0a81101]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1337) [server.jar:git-Spigot-f950f8e-0a81101]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1172) [server.jar:git-Spigot-f950f8e-0a81101]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-f950f8e-0a81101]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-f950f8e-0a81101]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-f950f8e-0a81101]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-f950f8e-0a81101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-f950f8e-0a81101]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-f950f8e-0a81101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [server.jar:git-Spigot-f950f8e-0a81101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [server.jar:git-Spigot-f950f8e-0a81101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.UnsupportedOperationException: Not supported.
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftZombie.setVillagerProfession(CraftZombie.java:50) ~[server.jar:git-Spigot-f950f8e-0a81101]
	at com.elmakers.mine.bukkit.entity.EntityZombieData.apply(EntityZombieData.java:26) ~[?:?]
	at com.elmakers.mine.bukkit.entity.EntityData.modify(EntityData.java:592) ~[?:?]
	at com.elmakers.mine.bukkit.entity.EntityData.spawn(EntityData.java:549) ~[?:?]
	at com.elmakers.mine.bukkit.entity.EntityData.spawn(EntityData.java:540) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.spawnMob(MagicController.java:4466) ~[?:?]
	at com.elmakers.mine.bukkit.magic.command.MagicMobCommandExecutor.onCommand(MagicMobCommandExecutor.java:134) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-f950f8e-0a81101]
	... 15 more
```

**Comment by NathanWolf** [comment]
I see the problem here- a zombie villager is no longer a zombie with a villager flag set.

I'll have to add support for actual zombie villagers.. but in doing some I would break backwards compatibility. I think for now I will change this mob type to a plain zombie or something- see fix in latest dev build #1764 or later.
