### ISSUE TITLE
Patronus Charm

### ISSUE THREAD

**Issue by Curtis73** [elBukkit/MagicPlugin#201]
Hey there, I'm not sure if I'm missing something out or if there is a bug, but for some reason whenever I or one of my players cast Expecto Patronum, the Patronus animal appears then vanishes and then it either says 'your spell fizzled' or 'your spell failed'.
Have I done anything wrong in the configs or is this a bug?

**Comment by NathanWolf** [comment]
I'll check it out- it's possible that some of the patronus overrides got broken since Spigot changed entity types around.

**Comment by NathanWolf** [comment]
Seems to be working for me. Do you have custom patronus data on your wand, maybe? Use "/wand describe" to check. Also check logs for errors, this sounds probably related to entity type.

**Comment by Curtis73** [comment]
`[07:43:40] [Server thread/WARN]: [Magic] Spell cast failed for patronus
java.lang.UnsupportedOperationException: Not supported.
at org.bukkit.craftbukkit.v1_11_R1.entity.CraftAbstractHorse.setVariant(CraftAbstractHorse.java:26) ~[minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at com.elmakers.mine.bukkit.action.builtin.EntityProjectileAction.setEntity(EntityProjectileAction.java:125) ~[Magic-6.5-SNAPSHOT.jar:?]
at com.elmakers.mine.bukkit.action.builtin.EntityProjectileAction.start(EntityProjectileAction.java:178) ~[Magic-6.5-SNAPSHOT.jar:?]
at com.elmakers.mine.bukkit.action.CompoundAction.perform(CompoundAction.java:78) ~[Magic-6.5-SNAPSHOT.jar:?]
at com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:38) ~[Magic-6.5-SNAPSHOT.jar:?]
at com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:222) ~[Magic-6.5-SNAPSHOT.jar:?]
at com.elmakers.mine.bukkit.action.ActionHandler.start(ActionHandler.java:163) ~[Magic-6.5-SNAPSHOT.jar:?]
at com.elmakers.mine.bukkit.spell.ActionSpell.onCast(ActionSpell.java:135) [Magic-6.5-SNAPSHOT.jar:?]
at com.elmakers.mine.bukkit.spell.BaseSpell.finalizeCast(BaseSpell.java:1274) [Magic-6.5-SNAPSHOT.jar:?]
at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1155) [Magic-6.5-SNAPSHOT.jar:?]
at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:961) [Magic-6.5-SNAPSHOT.jar:?]
at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1756) [Magic-6.5-SNAPSHOT.jar:?]
at com.elmakers.mine.bukkit.wand.Wand.cast(Wand.java:3397) [Magic-6.5-SNAPSHOT.jar:?]
at com.elmakers.mine.bukkit.wand.Wand.cast(Wand.java:3379) [Magic-6.5-SNAPSHOT.jar:?]
at com.elmakers.mine.bukkit.wand.Wand.performAction(Wand.java:4702) [Magic-6.5-SNAPSHOT.jar:?]
at com.elmakers.mine.bukkit.magic.listener.PlayerController.onPlayerInteract(PlayerController.java:486) [Magic-6.5-SNAPSHOT.jar:?]
at sun.reflect.GeneratedMethodAccessor366.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:232) [minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:199) [minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1382) [minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at net.minecraft.server.v1_11_R1.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:24) [minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at net.minecraft.server.v1_11_R1.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:1) [minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-d4f98a3-4448a7e]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

This error came up - I'm pretty sure it's related to entity types.

**Comment by NathanWolf** [comment]
Yup, exactly. You can remove that from wands with "/wand override patronus.variant" 

I also just removed horse variants completely from the code.

If you still want a thestral patronus, that would now be "/wand override patronus.type skeleton_horse"

**Comment by Curtis73** [comment]
Thank you!
