### ISSUE TITLE
Some fix?

### ISSUE THREAD

**Issue by Prowco** [elBukkit/MagicPlugin#207]
[19:43:37] [Craft Scheduler Thread - 3/WARN]: java.text.ParseException: Unparseable date: "Wed, 22 Feb 2017 22:23:31 GMT"
[19:43:37] [Craft Scheduler Thread - 3/WARN]: 	at java.text.DateFormat.parse(Unknown Source)
[19:43:37] [Craft Scheduler Thread - 3/WARN]: 	at com.elmakers.mine.bukkit.magic.MagicController$31.run(MagicController.java:4648)
[19:43:37] [Craft Scheduler Thread - 3/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[19:43:37] [Craft Scheduler Thread - 3/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[19:43:37] [Craft Scheduler Thread - 3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:43:37] [Craft Scheduler Thread - 3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:43:37] [Craft Scheduler Thread - 3/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by NathanWolf** [comment]
Was there more to this error message? Something like "Error occurred while checking resource pack"?

I'm assuming this happened while S3 was down. Should be a benign error but I will add some cleaner error reporting for when this happens.

**Comment by NathanWolf** [comment]
Or, I guess alternately have you put a different resource pack in Magic's config.yml ?

**Comment by NathanWolf** [comment]
The really weird thing is the date in your error message looks perfectly parseable... here's the format string I use:

```
EEE, dd MMM yyyy HH:mm:ss zzz
Wed, 22 Feb 2017 22:23:31 GMT
```

:|

**Comment by NathanWolf** [comment]
I pushed some better error handling for this, if you have any more information please let me know, I wasn't actually able to reproduce the problem.

**Comment by Prowco** [comment]
yes this msg is repeated every 1 minute.

**Comment by NathanWolf** [comment]
It will only happen once in the latest dev build. It would be great to have some more information about why this is happening to you though:

> have you put a different resource pack in Magic's config.yml ?

 If not, can you connect to this link? https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-RP-6-4.zip

If you don't mind me asking, what country are you in?

**Comment by Prowco** [comment]
No i dont change anything i just put example: potter thats all i change.
My country is costa rica latinamerica.
and yes iam using the last dev

**Comment by NathanWolf** [comment]
Thank you- that's very weird, seems to be a localized problem. Is the resource pack working?

You can turn off the automatic update checker by adding this to config.yml:
```
resource_pack_check_interval: 0
```

**Comment by Prowco** [comment]
Ok now this:

[16:23:29 WARN]: java.text.ParseException: Unparseable date: "Wed, 22 Feb 2017 22:23:31 GMT"
[16:23:29 WARN]:        at java.text.DateFormat.parse(Unknown Source)
[16:23:29 WARN]:        at com.elmakers.mine.bukkit.magic.MagicController$31.run(MagicController.java:4648)
[16:23:29 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[16:23:29 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[16:23:29 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[16:23:29 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[16:23:29 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:23:29 INFO]: [Vault] No new version available
[16:23:29 WARN]: [SpigetUpdate] Invalid SemVer versions specified [433] [442-SNAPSHOT]
[16:23:29 INFO]: [AnimatedFrames] The plugin is up-to-date.
[16:23:29 INFO]: [Quests] 3 Quest(s) loaded.
[16:23:29 INFO]: [Quests] 5 Event(s) loaded.
[16:23:29 INFO]: [Quests] 845 Phrase(s) loaded.
[16:23:29 INFO]: An error occurred while checking your resource pack (see logs): https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-potter-RP-6-4.zip
[16:23:29 INFO]: [Magic] Essentials found, hooked up custom item handler
[16:23:29 WARN]: [SpigetUpdate] Invalid SemVer versions specified [3123] [3132-SNAPSHOT]
[16:23:29 INFO]: [NickNamer] The plugin is up-to-date.
[16:23:29 INFO]: [Magic] Loading lost wand data
[16:23:29 INFO]: [Magic] Loaded 0 lost wands
[16:23:29 INFO]: [Magic] Loading automata data
[16:23:29 INFO]: [Magic] Loaded 0 automata
[16:23:29 INFO]: [Magic] Finished loading data.

**Comment by Prowco** [comment]
Basically the same error.

**Comment by NathanWolf** [comment]
You will still see the error unless you update to the latest dev build, or turn the resource pack off completely.

The setting I gave you should make it so it doesn't repeat, it just shows up once on load.

**Comment by Prowco** [comment]
I understand ok. thanks
