### ISSUE TITLE
Can't access Spell inevntory

### ISSUE THREAD

**Issue by Shadow82828** [elBukkit/MagicPlugin#221]
Hi,
 yesterday i installed your plugin... first a compliment: it's really aweseome...
But i noticed i can't change the spells on a wand, when it got more than one, which should be possible with q by default... if i press q, the wand goes down a little but no inventory opens up...
Im using spigot 1.10.2

Thanks

**Comment by NathanWolf** [comment]
Are there any errors in your logs? I assume you haven't done any config customization yet?

**Comment by Shadow82828** [comment]
Actually there is... havent noticed yet... 
the console prints this:
[16:17:26 WARN]: [Magic] Task #1773201 for Magic v6.9.4 generated an exception
java.lang.NoSuchMethodError: com.elmakers.mine.bukkit.wand.Wand.getDropAction()Lcom/elmakers/mine/bukkit/wand/WandAction;
at com.elmakers.mine.bukkit.magic.DropActionTask.run(DropActionTask.java:14) ~[?:?]
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]

**Comment by NathanWolf** [comment]
Hm, I wonder if I may have uploaded a bad build? I haven't seen this from anyone else, though, which seems odd. Can you please try the latest dev build?

http://jenkins.elmakers.com/job/MagicPlugin/2074/com.elmakers.mine.bukkit.plugins$Magic/artifact/com.elmakers.mine.bukkit.plugins/Magic/7.0-SNAPSHOT/Magic-7.0-SNAPSHOT.jar

**Comment by Shadow82828** [comment]
sure thing, ill give it a try

**Comment by Shadow82828** [comment]
thx mate... works perfectly fine now :)
