### ISSUE TITLE
Latest build won't load for me

### ISSUE THREAD

**Issue by malonnnn** [elBukkit/MagicPlugin#227]
Log error

`[21:45:14] [Server thread/ERROR]: com/elmakers/mine/bukkit/bstats/Metrics$CustomChart initializing Magic v7.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/elmakers/mine/bukkit/bstats/Metrics$CustomChart
	at com.elmakers.mine.bukkit.magic.MagicPlugin.onLoad(MagicPlugin.java:155) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:307) [patched_1.11.2.jar:git-Paper-1095]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:208) [patched_1.11.2.jar:git-Paper-1095]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1095]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: com.elmakers.mine.bukkit.bstats.Metrics$CustomChart
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.11.2.jar:git-Paper-1095]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.11.2.jar:git-Paper-1095]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	... 5 more`

**Comment by NathanWolf** [comment]
Er- that's weird, I am running this build on my dev server. Did you build this yourself?

**Comment by NathanWolf** [comment]
Oh, actually I guess I lied, there have been changes since the build I'm running.

@killme er any chance your recent dependency changes have broken something?

**Comment by NathanWolf** [comment]
Oh yeah.. it's definitely broken, sorry. I'll see what I can do. *shakes fist*

**Comment by killme** [comment]
Aww shit. I broke the shading configuration. Try changing the `<scope>`
of the statistics to `source` rather than `provided`.

**Comment by NathanWolf** [comment]
Ah yeah totally- thanks for the quick response! Used to be "compile", but should be "source"? I don't know the difference.. but yeah def shouldn't be "provided" :)

**Comment by killme** [comment]
I guess it's compile. I get them mixed up all the time. `source` is
probably not valid.

**Comment by NathanWolf** [comment]
Cool, thanks- looks all good now, fixed in #2108
