### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Blamo27** [elBukkit/MagicPlugin#242]
Hello !

My server crashed due to Magic plugin.

Can you fix this ?

```
[16:30:34] [Server thread/WARN]: Excessive velocity set detected: tried to set velocity of entity #35023213 to (0.0,-4.242640687119285,-4.242640687119285).
[16:30:34] [Server thread/WARN]: java.lang.Exception: Stack trace
[16:30:34] [Server thread/WARN]: 	at java.lang.Thread.dumpStack(Thread.java:1333)
[16:30:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.setVelocity(CraftEntity.java:213)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.action.builtin.VelocityAction.perform(VelocityAction.java:143)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:38)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:237)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.action.CompoundAction.perform(CompoundAction.java:93)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:38)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:237)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.action.CompoundAction.perform(CompoundAction.java:93)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:38)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:237)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.action.ActionHandler.start(ActionHandler.java:178)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.spell.ActionSpell.onCast(ActionSpell.java:123)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.spell.BaseSpell.finalizeCast(BaseSpell.java:1146)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1047)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:875)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1598)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.wand.Wand.cast(Wand.java:3557)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.wand.Wand.cast(Wand.java:3539)
[16:30:34] [Server thread/WARN]: 	at com.elmakers.mine.bukkit.magic.listener.PlayerController.onPlayerInteract(PlayerController.java:401)
[16:30:34] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor314.invoke(Unknown Source)
[16:30:34] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:30:34] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:30:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[16:30:34] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[16:30:34] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:30:34] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[16:30:34] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[16:30:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228)
[16:30:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195)
[16:30:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107)
[16:30:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:626)
[16:30:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40)
[16:30:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10)
[16:30:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:30:34] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:30:34] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:30:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:30:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[16:30:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[16:30:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[16:30:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[16:30:34] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by NathanWolf** [comment]
The current release of Magic has excessive velocity protection built in, but I'm pretty done updating Magic 5 (for 1.8)

**Comment by killme** [comment]
This stacktrace doesn't really look like something that would crash your server normally. While it is true that the networking layer only shows velocities up to 4 correctly, and very high velocities can crash a server, it doesn't seem to be the case here. A velocity of 4 should be completely fine.

Perhaps something else is causing this? What's your server version and your magic version? Could you paste a longer log from when the crash happened?

**Comment by NathanWolf** [comment]
I'm thinking this is Paper, it has velocity checks. I don't think this would be a "server crash" exactly but in plain spigot without the checks it does cause some client crashing and other serious issues.

I really hope you can update off of 1.8 at some point!

**Comment by Blamo27** [comment]
I got this too, my server crashed again

`[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: The server has stopped responding!
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: Please report this to PaperSpigot directly!
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: PaperSpigot version: git-PaperSpigot-"4c7641d" (MC: 1.8.8)
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: ------------------------------
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to PaperSpigot!):
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: ------------------------------
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: Current Thread: Server thread
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: 	PID: 16 | Suspended: false | Native: false | State: RUNNABLE
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: 	Stack:
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.Block.a(Block.java:284)
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.World.getCubes(World.java:1221)
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.Entity.move(Entity.java:518)
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.EntityItem.t_(EntityItem.java:74)
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1650)
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.World.g(World.java:1617)
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1450)
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:600)
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:846)
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[18:14:48] [PaperSpigot Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:745)`

**Comment by NathanWolf** [comment]
That's a very truncated log, but from what I can see does not look Magic related, you may have a corrupt chunk or.. something, I dunno. Error happened in vanilla code, though.

Are you stuck on 1.8 for some reason? It's like 3 years old, very hard to support that.

**Comment by Blamo27** [comment]
We'll update our server to 1.11 when the new website will be finished.
But in the mean time, we need to fix that to continue the developpment.
Theses two crashes are probably linked to a malicious user that is waiting the perfect timing to hit the server when there is the most players.

**Comment by NathanWolf** [comment]
Ok, well I don't want your server crashing- try this build:

http://jenkins.elmakers.com/view/Plugins/job/MagicPlugin-1.8/44/com.elmakers.mine.bukkit.plugins$Magic/

For the record, this was a _really_ tedious change to have to re-do, and I am, at some point, going to flat out refuse to update the 1.8 and 1.7 builds of Magic- it's just getting completely ridiculous!

**Comment by Blamo27** [comment]
Okey, i'm gonna test this version.
Thanks.

**Comment by NathanWolf** [comment]
Everything good now?

**Comment by Blamo27** [comment]
@NathanWolf Yes, thanks !
