### ISSUE TITLE
NullPointerException: null on mgive wand item.

### ISSUE THREAD

**Issue by mibby** [elBukkit/MagicPlugin#243]
Paper dev 1121 (Spigot 1.12)
Magic dev 2160

```
hat_book:
    name: Book Hat
    mode: cast
    active_spell: magichat
    icon: diamond_shovel:1
    indestructible: true
    locked: true
    keep: true
    effect_color: '888888'
    spells:
        - magichat
```

```
[20:13:53] [Server thread/INFO]: player issued server command: /mgive player hat_book
[20:10:51] [Server thread/WARN]: [Magic] Error creating item: hat_book
java.lang.NullPointerException: null
	at com.elmakers.mine.bukkit.magic.MagicController.createItem(MagicController.java:4156) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.createItem(MagicController.java:4068) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicPlugin.createItem(MagicPlugin.java:422) ~[?:?]
	at com.elmakers.mine.bukkit.magic.command.MagicGiveCommandExecutor.onCommand(MagicGiveCommandExecutor.java:98) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.jar:git-Paper-1121]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.jar:git-Paper-1121]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:668) ~[patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1424) ~[patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1229) ~[patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.jar:git-Paper-1121]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:416) [patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1121]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by NathanWolf** [comment]
Should be diamond_spade instead of diamond_shovel

Also should be a better error message, though- so I will look into that, thanks!

**Comment by NathanWolf** [comment]
Dev build 2162 will have better logs and in-game messages for when wands have an invalid icon in configs.

**Comment by mibby** [comment]
Thanks. :) Any reason why a resource pack listens for diamond_shovel but magic requires it to be spade? Or is it just down to bukkit's implementation of that item?

**Comment by NathanWolf** [comment]
Difference between Mojang item names (RP) and Bukkit item names (code).
