### ISSUE TITLE
NoSuchMethodException - An error occurred, handling of tile entities may not work well

### ISSUE THREAD

**Issue by mibby** [elBukkit/MagicPlugin#253]
Magic v6.9.15 (release build)
Paper dev 1170 (Spigot 1.12.1)

Broke with minecraft update 1.12.1?
```
[13:31:23] [Server thread/INFO]: [Magic] Enabling Magic v6.9.15
[13:31:23] [Server thread/WARN]: An error occurred, handling of tile entities may not work well
java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.TileEntity.a(net.minecraft.server.v1_12_R1.NBTTagCompound)
	at java.lang.Class.getMethod(Class.java:1786) ~[?:1.8.0_144]
	at com.elmakers.mine.bukkit.utility.NMSUtils.<clinit>(NMSUtils.java:668) [Magic-6.9.15.jar:?]
	at com.elmakers.mine.bukkit.magic.MagicPlugin.onEnable(MagicPlugin.java:168) [Magic-6.9.15.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.1.jar:git-Paper-1170]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.1.jar:git-Paper-1170]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.1.jar:git-Paper-1170]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [patched_1.12.1.jar:git-Paper-1170]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:325) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.1.jar:git-Paper-1170]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[13:31:23] [Server thread/INFO]: [Magic] EffectLib initialized
```

**Comment by NathanWolf** [comment]
Fixed in latest dev build, though with my CI server being dead that means you'll have to wait for the next release or else build it yourself.

The error should be pretty benign though, only really effects copying complex tile entities or loading them from schematics.

**Comment by mibby** [comment]
I tried building it myself but it just failed and timed out pom downloads due to repository dependencies linking back to the dead CI server. So I guess I'll just wait for the next release. 

Thanks for the fix. :)
