### ISSUE TITLE
Strange error in Minecraft 1.12.1

### ISSUE THREAD

**Issue by alexchandel** [elBukkit/MagicPlugin#254]
Using the latest MagicPlugin 6.9.15, on Spigot 1.12.1, I get this error loading:

```
[01:19:45 INFO]: [Magic] Enabling Magic v6.9.15
[01:19:46 WARN]: An error occurred, handling of tile entities may not work well
java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.TileEntity.a(net.minecraft.server.v1_12_R1.NBTTagCompound)
        at java.lang.Class.getMethod(Class.java:1786) ~[?:1.8.0_112]
        at com.elmakers.mine.bukkit.utility.NMSUtils.<clinit>(NMSUtils.java:668) [Magic-6.9.15.jar:?]
        at com.elmakers.mine.bukkit.magic.MagicPlugin.onEnable(MagicPlugin.java:168) [Magic-6.9.15.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot-1.12.1.jar:git-Spigot-5340a52-b587878]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.1.jar:git-Spigot-5340a52-b587878]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.1.jar:git-Spigot-5340a52-b587878]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:380) [spigot-1.12.1.jar:git-Spigot-5340a52-b587878]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [spigot-1.12.1.jar:git-Spigot-5340a52-b587878]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.1.jar:git-Spigot-5340a52-b587878]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.1.jar:git-Spigot-5340a52-b587878]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.1.jar:git-Spigot-5340a52-b587878]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.1.jar:git-Spigot-5340a52-b587878]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.1.jar:git-Spigot-5340a52-b587878]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
[01:19:46 INFO]: [Magic] EffectLib initialized
[01:19:46 INFO]: [Magic] Loading config.yml
```

The website appears to be down, and I can't find the link to the 7.0 snapshot on either the dev.bukkit.org or curse pages, so this is the latest version I could test.

**Comment by NathanWolf** [comment]
This is fixed in the latest dev build, but you're right that the CI server is down so it'll have to wait for next release.

The error itself is fairly benign, you can continue using the current release without any major issues.
