### ISSUE TITLE
Error PacketPlayOutChat

### ISSUE THREAD

**Issue by paperrain** [elBukkit/MagicPlugin#287]
I have this error spamming the console:

https://pastebin.com/YBeh8GGN

Version: 1.12.2 Spigot
Magic: 6.9.20

**Comment by NathanWolf** [comment]
This problem is with some action bar health plugin that needs updating, nothing to do with Magic:

```
[17:50:35] [Server thread/WARN]:    at com.zeshanaslam.actionhealth.Main.sendActionBar(Main.java:289)
[17:50:35] [Server thread/WARN]:    at com.zeshanaslam.actionhealth.Main.sendHealth2(Main.java:351)
[17:50:35] [Server thread/WARN]:    at com.zeshanaslam.actionhealth.Main.onBow(Main.java:200)
```
