### ISSUE TITLE
Error with MMobs

### ISSUE THREAD

**Issue by 4kz** [elBukkit/MagicPlugin#307]
Error:

```
[00:07:57] [Server thread/WARN]: [Magic] Error creating item: pitch soldier+
java.lang.Exception: Invalid item key: pitch soldier+
	at com.elmakers.mine.bukkit.item.ItemData.<init>(ItemData.java:38) ~[Magic-6.9.19.jar:?]
	at com.elmakers.mine.bukkit.magic.listener.ItemController.getOrCreate(ItemController.java:60) [Magic-6.9.19.jar:?]
	at com.elmakers.mine.bukkit.magic.MagicController.getOrCreateItem(MagicController.java:4485) [Magic-6.9.19.jar:?]
	at com.elmakers.mine.bukkit.entity.EntityData.<init>(EntityData.java:334) [Magic-6.9.19.jar:?]
	at com.elmakers.mine.bukkit.magic.listener.MobController.load(MobController.java:35) [Magic-6.9.19.jar:?]
	at com.elmakers.mine.bukkit.magic.MagicController.finalizeLoad(MagicController.java:1532) [Magic-6.9.19.jar:?]
	at com.elmakers.mine.bukkit.magic.ConfigurationLoadTask$1.run(ConfigurationLoadTask.java:137) [Magic-6.9.19.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-b66ad9e-e1fb9cb]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-b66ad9e-e1fb9cb]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
```

MMob:
```

niBBaplus:
  chestplate: "307"
  leggings: "pitch soldier+"
  helmet: "171:15"
  boots: ""
  item: "iron_axe"
  name: ""
  type: wither_skeleton
  health: 16
  default_drops: false
  drops:
  - exp_bottle@2
  attributes:
    generic_follow_range: 30
    generic_attack_damage: -2
```

**Comment by NathanWolf** [comment]
"pitch soldier+" doesn't seem like a valid key. Did you try to put that in your items.yml?

Generally they don't have spaces in them, and probably not a good idea to have special characters either.

**Comment by 4kz** [comment]
I don't really know how could I put the name of the mob as leggings, I swear I double-checked that
