### ISSUE TITLE
chain of warnings 

### ISSUE THREAD

**Issue by sx34** [elBukkit/MagicPlugin#313]
I'm sorry if this causes a lot of trouble for you, but what does this mean, exactly?:

```
[03:51:44 WARN]: [MagicWorlds] Error loading handler: com.elmakers.mine.bukkit.magicworlds.populator.builtin.ReplacePopulator
[03:51:44 WARN]: java.lang.NoClassDefFoundError: com/elmakers/mine/bukkit/api/block/ModifyType
[03:51:44 WARN]:        at com.elmakers.mine.bukkit.magicworlds.populator.MagicBlockPopulator.<init>(MagicBlockPopulator.java:19)
[03:51:44 WARN]:        at com.elmakers.mine.bukkit.magicworlds.populator.builtin.ReplacePopulator.<init>(ReplacePopulator.java:15)
[03:51:44 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:51:44 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[03:51:44 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:51:44 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[03:51:44 WARN]:        at java.lang.Class.newInstance(Class.java:442)
[03:51:44 WARN]:        at com.elmakers.mine.bukkit.magicworlds.populator.MagicChunkHandler.createChunkPopulator(MagicChunkHandler.java:81)
[03:51:44 WARN]:        at com.elmakers.mine.bukkit.magicworlds.populator.MagicChunkHandler.load(MagicChunkHandler.java:29)
[03:51:44 WARN]:        at com.elmakers.mine.bukkit.magicworlds.MagicWorld.load(MagicWorld.java:76)
[03:51:44 WARN]:        at com.elmakers.mine.bukkit.magicworlds.MagicWorldsController.load(MagicWorldsController.java:109)
[03:51:44 WARN]:        at com.elmakers.mine.bukkit.magicworlds.MagicWorldsController.initialize(MagicWorldsController.java:57)
[03:51:44 WARN]:        at com.elmakers.mine.bukkit.magicworlds.MagicWorldsPlugin.initialize(MagicWorldsPlugin.java:113)
[03:51:44 WARN]:        at com.elmakers.mine.bukkit.magicworlds.MagicWorldsPlugin.onEnable(MagicWorldsPlugin.java:105)
[03:51:44 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[03:51:44 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[03:51:44 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[03:51:44 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342)
[03:51:44 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314)
[03:51:44 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.<init>(CraftServer.java:252)
[03:51:44 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.<init>(PlayerList.java:69)
[03:51:44 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedPlayerList.<init>(SourceFile:14)
[03:51:44 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:179)
[03:51:44 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504)
[03:51:44 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by NathanWolf** [comment]
That means you're using the newest MagicWorlds, but an older Magic- please update Magic to latest build, or downgrade MagicWorlds to 1.4

**Comment by NathanWolf** [comment]
I'm hoping that helped, if not please re-open!
