### ISSUE TITLE
Issue?

### ISSUE THREAD

**Issue by AntonioC94** [elBukkit/MagicPlugin#357]
So.. I have this issue in cmd and I dont really know what im doing when appear this message, If it helps you, I'll leave it here ^^ 
```
[20:57:54] [Server thread/ERROR]: Could not pass event InventoryCreativeEvent to Magic v7.3.7-dbf3886
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2045) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: com.elmakers.mine.bukkit.magic.MagicController$PluginNotLoadedException
	at com.elmakers.mine.bukkit.magic.MagicController.getMage(MagicController.java:317) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.getMage(MagicController.java:253) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.getMageFromEntity(MagicController.java:225) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.getMage(MagicController.java:261) ~[?:?]
	at com.elmakers.mine.bukkit.magic.listener.InventoryController.onInventoryClick(InventoryController.java:116) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	... 15 more
```

**Comment by AntonioC94** [comment]
Am yes! Sometimes, I have this issue when i start up the server
```
[23:23:45 WARN]: [Magic] Player data request for ba04c878-7a1a-4c35-828a-e545a5e8cf8d (AntonioC94) failed, plugin not loaded yet
[23:23:45 ERROR]: Error occurred while enabling Magic v7.3.7-dbf3886 (Is it up to date?)
com.elmakers.mine.bukkit.magic.MagicController$PluginNotLoadedException: null
        at com.elmakers.mine.bukkit.magic.MagicController.getMage(MagicController.java:317) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.getMage(MagicController.java:253) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.getMageFromEntity(MagicController.java:225) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.getMage(MagicController.java:261) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.finalizeIntegration(MagicController.java:1225) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.finalizeLoad(MagicController.java:1768) ~[?:?]
        at com.elmakers.mine.bukkit.magic.ConfigurationLoadTask.run(ConfigurationLoadTask.java:139) ~[?:?]
        at com.elmakers.mine.bukkit.magic.ConfigurationLoadTask.runNow(ConfigurationLoadTask.java:35) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:1869) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:1861) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.load(MagicController.java:1898) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.initialize(MagicController.java:876) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicPlugin.initialize(MagicPlugin.java:184) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicPlugin.onEnable(MagicPlugin.java:178) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:752) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.Bukkit.reload(Bukkit.java:525) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by NathanWolf** [comment]
That's still a "plugin not loaded" error. Do you get this on a fresh server start? Are there any errors further up?

Do not use the `/reload` command...

**Comment by AntonioC94** [comment]
I freshed the server removing the magic file and i have the same issue 
```
[01:21:45 WARN]: [Magic] Player data request for ba04c878-7a1a-4c35-828a-e545a5e8cf8d (AntonioC94) failed, plugin not loaded yet
[01:21:45 ERROR]: Could not pass event PlayerAnimationEvent to Magic v7.3.7-dbf3886
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1440) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:24) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:1) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: com.elmakers.mine.bukkit.magic.MagicController$PluginNotLoadedException
        at com.elmakers.mine.bukkit.magic.MagicController.getMage(MagicController.java:317) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.getMage(MagicController.java:253) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.getMageFromEntity(MagicController.java:225) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.getMage(MagicController.java:261) ~[?:?]
        at com.elmakers.mine.bukkit.magic.listener.PlayerController.onPlayerAnimate(PlayerController.java:400) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        ... 15 more
```

**Comment by AntonioC94** [comment]
I dont really know what is happening, I can send you all the log maybe?

**Comment by NathanWolf** [comment]
Yes please. Easiest way is to go to https://hastebin.com, paste your whole log, and then paste the link back here.

I'm expecting there is an error before all of this, while your server is starting up, before any players log in.

**Comment by AntonioC94** [comment]
Let me few minutes, By the moment i cant save the log in hastebin

**Comment by AntonioC94** [comment]
By the way you have the log here https://pastebin.com/NkdBFdCq , I will send you the log in https://hastebin.com if i can .

**Comment by NathanWolf** [comment]
Pastebin is fine, thank you! I’ll look at this when I can and let you know what’s up.

**Comment by NathanWolf** [comment]
So can you tell me what’s going on here? Do you have a plugin that issued the /reload command for some reason? 

Or is a player logging in immediately after startup and doing /reload?

As it says in the logs the reload command isn’t supported and shouldn’t really be used. I think it is what is causing your problems. 

I can see if Magic can be ok with using that command, but in general you really should avoid using it.

**Comment by AntonioC94** [comment]
Well.. I don't really know, what I am doing when this issues appear. I am testing and doing /reload to test my owns plugins, so.. the command /reload is maybe a problem to use magic??

**Comment by AntonioC94** [comment]
I was using the command /stop to restart the server a load the plugins more "clearly" and by the way i dont have issues by Magic

**Comment by AntonioC94** [comment]
Yes well.. Is more quick to me do the command reload to test my little plugins :P
