### ISSUE TITLE
Fail to load player data

### ISSUE THREAD

**Issue by TheGhostBoy5566** [elBukkit/MagicPlugin#368]
Every time I go into minecraft and go to my server my magic wands dont work

**Comment by NathanWolf** [comment]
Please provide some more information. For starters:

1. Server version
2. Plugin version
3. Startup logs- assume you are getting some kind of error from the title of this issue, seeing the error would be helpful.

**Comment by TheGhostBoy5566** [comment]
1.8 and I am using 5.5.5

**Comment by TheGhostBoy5566** [comment]
[12:57:22 WARN]: [Magic] Failed to load player data for TheGhostBoy5566
java.lang.NullPointerException
        at com.elmakers.mine.bukkit.wand.Wand.<init>(Wand.java:265) ~[Magic-5.5.5.jar:?]
        at com.elmakers.mine.bukkit.magic.Mage.load(Mage.java:655) [Magic-5.5.5.jar:?]
        at com.elmakers.mine.bukkit.magic.MagicController$1$1.run(MagicController.java:222) [Magic-5.5.5.jar:?]
        at com.elmakers.mine.bukkit.data.YamlMageDataStore.load(YamlMageDataStore.java:50) [Magic-5.5.5.jar:?]
        at com.elmakers.mine.bukkit.magic.MagicController$1.run(MagicController.java:219) [Magic-5.5.5.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
