### ISSUE TITLE
Quest Objectives

### ISSUE THREAD

**Issue by christophe6** [elBukkit/MagicPlugin#379]
Quests recently changed something in their files which would break all modules. This is probably why the magic quests module does not work anymore. Could you please compile against the newest version?
I am getting this error when Magic is inside the modules folder but when it is not, no errors are logged. (I know there's no reference to magic inside this error.)

`[14:32:37] [Server thread/ERROR]: Error occurred while enabling Quests v3.3.4-b316 (Is it up to date?)
java.lang.NoClassDefFoundError: com/herocraftonline/heroes/characters/skill/ActiveSkill
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_151]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_151]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_151]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191) ~[Spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[Spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411) ~[?:1.8.0_151]
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_151]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_151]
	at me.blackvein.quests.Quests.loadModule(Quests.java:566) ~[?:?]
	at me.blackvein.quests.Quests.loadModules(Quests.java:542) ~[?:?]
	at me.blackvein.quests.Quests.onEnable(Quests.java:182) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[Spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: com.herocraftonline.heroes.characters.skill.ActiveSkill
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	... 33 more`

**Comment by NathanWolf** [comment]
Did you put Magic.jar in the Quests modules folder? You need to put the MagicQuests jar in there, and leave Magic in the plugins folder:

http://jenkins.elmakers.com/job/MagicQuests/90/com.elmakers.mine.bukkit.plugins$MagicQuests/

Version 1.1 of MagicQuests was updated to work with recent Quests. You're right, there was a breaking  change to the Quests API but I have already updated.

**Comment by christophe6** [comment]
Oh I put the Magic.jar in the modules folder :/. I am sorry! Thank you!
