### ISSUE TITLE
Recall bug

### ISSUE THREAD

**Issue by Elsopeen** [elBukkit/MagicPlugin#43]
Hello,
I have an issue with the recall spell : we've just change our server from bukkit to spigot and, since I added new warp points, the spells Recall, warpmenu and warpunlock were bugged.
Here is my spell configuration : 
recall:
  parameters:
    delay: 500
    commands:
      hub:
        name: BlueBoxCraft Hub
        description: Retour au Hub
        icon: nether_star
        command: mvtp ASIKOO.XYZ
        op: true
    warps:
      UTOPIA:
        name: Utopia
        description: Spawn d'Utopia
        locked: false
        icon: blaze_powder
      ZI1:
        name: Zone Industrielle 1
        description: Usines de productions communes
        locked: false
        icon: furnace
      ZI2:
        name: Zone Industrielle 2
        description: Usines de productions communes
        locked: false
        icon: piston
      MAGIC:
        name: Ecole de Magie
        description: Venez apprendre la magie !
        locked: false
        icon: bookshelf
      GALLIFREY:
        name: Gallifrey
        description: Planète des TARDIS
        locked: false
        icon: beacon
      GAMING_ROOM:
        name: Gaming Room
        description: Lieu des mini-jeux
        locked: false
        icon: emerald_block
      MUSEUM-PPM:
        name: Musee des Items Uniques
        description: Cree par Pordrack, Play-Mobile et Moshito
        locked: false
        icon: gold_block

And here is the error when we cast this spell : 
[15:40:59 INFO]: Elsopeen issued server command: /cast recall
[15:41:00 WARN]: [Magic] Task #74 for Magic v5.5-SNAPSHOT generated an exception
java.lang.NullPointerException
at com.elmakers.mine.bukkit.block.MaterialAndData.getItemStack(MaterialAndData.java:490) ~[?:?]
at com.elmakers.mine.bukkit.action.builtin.RecallAction.perform(RecallAction.java:559) ~[?:?]
at com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:38) ~[?:?]
at com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:237) ~[?:?]
at com.elmakers.mine.bukkit.batch.ActionBatch.process(ActionBatch.java:30) ~[?:?]
at com.elmakers.mine.bukkit.magic.Mage.processPendingBatches(Mage.java:881) ~[?:?]
at com.elmakers.mine.bukkit.magic.MagicController.processPendingBatches(MagicController.java:1065) ~[?:?]
at com.elmakers.mine.bukkit.magic.BatchUpdateTask.run(BatchUpdateTask.java:12) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_openmod.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_openmod.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [minecraft_openmod.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_openmod.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_openmod.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_openmod.jar:git-Spigot-e4d4710-e1ebe52]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

Hoping you'll can find quickly the solution,
Best regards,
Elsopeen

**Comment by NathanWolf** [comment]
Hm - I don't think "piston" is a valid material - try changing that to something else?

I will also test this out when I can, and make it so there's a better/more informative error message when this happens!

**Comment by Elsopeen** [comment]
Thanks again for your advices and your quick answer. I changed piston to a block in the material list and now it works great. Thanks again
Best regards,
Elsopeen

**Comment by NathanWolf** [comment]
Glad that helped! I am going to reopen this to remind me to handle this case better :) thanks!
