### ISSUE TITLE
Could not pass event PlayerPickupArrowEvent to Magic

### ISSUE THREAD

**Issue by mibby** [elBukkit/MagicPlugin#430]
Paper dev 373 (Spigot 1.13.1)
Magic dev 2797

```
[02:52:18] [Server thread/ERROR]: Could not pass event PlayerPickupArrowEvent to Magic v7.6.15-SNAPSHOT-1fbe3b1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.1.jar:git-Paper-373]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityArrow.d(EntityArrow.java:500) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityThrownTrident.d(EntityThrownTrident.java:142) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityHuman.c(EntityHuman.java:496) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityHuman.k(EntityHuman.java:471) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2182) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:163) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:402) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.PlayerConnection.Y_(PlayerConnection.java:145) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:253) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:130) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1118) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-373]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.server.v1_13_R2.EntityThrownTrident cannot be cast to class net.minecraft.server.v1_13_R2.EntityItem (net.minecraft.server.v1_13_R2.EntityThrownTrident and net.minecraft.server.v1_13_R2.EntityItem are in unnamed module of loader 'app')
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftItem.getHandle(CraftItem.java:32) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftItem.getHandle(CraftItem.java:17) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.getUniqueId(CraftEntity.java:495) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_13_R2.metadata.EntityMetadataStore.disambiguate(EntityMetadataStore.java:21) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_13_R2.metadata.EntityMetadataStore.disambiguate(EntityMetadataStore.java:10) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.metadata.MetadataStoreBase.hasMetadata(MetadataStoreBase.java:79) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.hasMetadata(CraftEntity.java:560) ~[patched_1.13.1.jar:git-Paper-373]
	at com.elmakers.mine.bukkit.magic.listener.PlayerController.onPlayerPrePickupItem(PlayerController.java:719) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor988.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-373]
	... 18 more
[02:52:18] [Server thread/ERROR]: Could not pass event PlayerPickupArrowEvent to WorldGuard v7.0.0-SNAPSHOT;0dc5781
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.1.jar:git-Paper-373]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityArrow.d(EntityArrow.java:500) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityThrownTrident.d(EntityThrownTrident.java:142) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityHuman.c(EntityHuman.java:496) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityHuman.k(EntityHuman.java:471) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2182) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:163) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:402) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.PlayerConnection.Y_(PlayerConnection.java:145) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:253) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:130) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1118) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-373]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.server.v1_13_R2.EntityThrownTrident cannot be cast to class net.minecraft.server.v1_13_R2.EntityItem (net.minecraft.server.v1_13_R2.EntityThrownTrident and net.minecraft.server.v1_13_R2.EntityItem are in unnamed module of loader 'app')
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftItem.getHandle(CraftItem.java:32) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftItem.getHandle(CraftItem.java:17) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.getUniqueId(CraftEntity.java:495) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.hashCode(CraftEntity.java:547) ~[patched_1.13.1.jar:git-Paper-373]
	at com.sk89q.worldguard.bukkit.listener.debounce.legacy.EntityEntityEventDebounce$Key.hashCode(EntityEntityEventDebounce.java:62) ~[?:?]
	at com.google.common.base.Equivalence$Equals.doHash(Equivalence.java:351) ~[patched_1.13.1.jar:git-Paper-373]
	at com.google.common.base.Equivalence.hash(Equivalence.java:117) ~[patched_1.13.1.jar:git-Paper-373]
	at com.google.common.cache.LocalCache.hash(LocalCache.java:1851) ~[patched_1.13.1.jar:git-Paper-373]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4153) ~[patched_1.13.1.jar:git-Paper-373]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[patched_1.13.1.jar:git-Paper-373]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[patched_1.13.1.jar:git-Paper-373]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[patched_1.13.1.jar:git-Paper-373]
	at com.sk89q.worldguard.bukkit.listener.debounce.legacy.AbstractEventDebounce.debounce(AbstractEventDebounce.java:50) ~[?:?]
	at com.sk89q.worldguard.bukkit.listener.debounce.legacy.EntityEntityEventDebounce.debounce(EntityEntityEventDebounce.java:34) ~[?:?]
	at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onPlayerPickupItem(EventAbstractionListener.java:805) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor810.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-373]
	... 18 more
[02:52:18] [Server thread/ERROR]: Could not pass event PlayerPickupArrowEvent to mcMMO v1.6.0-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.1.jar:git-Paper-373]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityArrow.d(EntityArrow.java:500) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityThrownTrident.d(EntityThrownTrident.java:142) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityHuman.c(EntityHuman.java:496) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityHuman.k(EntityHuman.java:471) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2182) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:163) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:402) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.PlayerConnection.Y_(PlayerConnection.java:145) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:253) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:130) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1118) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-373]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-373]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.server.v1_13_R2.EntityThrownTrident cannot be cast to class net.minecraft.server.v1_13_R2.EntityItem (net.minecraft.server.v1_13_R2.EntityThrownTrident and net.minecraft.server.v1_13_R2.EntityItem are in unnamed module of loader 'app')
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftItem.getHandle(CraftItem.java:32) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftItem.getHandle(CraftItem.java:17) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.getUniqueId(CraftEntity.java:495) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_13_R2.metadata.EntityMetadataStore.disambiguate(EntityMetadataStore.java:21) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_13_R2.metadata.EntityMetadataStore.disambiguate(EntityMetadataStore.java:10) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.metadata.MetadataStoreBase.hasMetadata(MetadataStoreBase.java:79) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.hasMetadata(CraftEntity.java:560) ~[patched_1.13.1.jar:git-Paper-373]
	at com.gmail.nossr50.listeners.PlayerListener.onPlayerPickupItem(PlayerListener.java:294) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-373]
	... 18 more
```

**Comment by NathanWolf** [comment]
I'm going to go ahead and say that's a paper spigot bug (or possibly just a spigot bug, though I haven't seen it myself, and I have picked up tridents)

My code is just calling an API method here, ItemStack.hasMetadata. Something's gone wrong internally with how the server is treading the dropped trident item entity.

**Comment by mibby** [comment]
Seems to have been fixed here. https://github.com/PaperMC/Paper/commit/0db94d4fcac2715f70b221eabfdcbd70bd13332d

Apologies!

**Comment by mibby** [comment]
Seems to have been fixed here.
https://github.com/PaperMC/Paper/commit/0db94d4fcac2715f70b221eabfdcbd70bd13332d

My apologies!

**Comment by mibby** [comment]
Seems to have been fixed here.
https://github.com/PaperMC/Paper/commit/0db94d4fcac2715f70b221eabfdcbd70bd13332d

My apologies!

**Comment by mibby** [comment]
Seems to have been fixed here. 
https://github.com/PaperMC/Paper/commit/0db94d4fcac2715f70b221eabfdcbd70bd13332d

My apologies!

**Comment by mibby** [comment]
Seems to have been fixed here. 
https://github.com/PaperMC/Paper/commit/0db94d4fcac2715f70b221eabfdcbd70bd13332d

My apologies!

**Comment by mibby** [comment]
Github experiencing issues? :(
