### ISSUE TITLE
WorldEdit breaking changes - new vector implementation.

### ISSUE THREAD

**Issue by mibby** [elBukkit/MagicPlugin#437]
New WorldEdit dev builds added a new vector implementation. It is now Vector3 / BlockVector3.

```
[15:38:06] [Server thread/WARN]: [Magic] Task #60847 for Magic v7.6.16-SNAPSHOT-925e037 generated an exception
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
	at com.elmakers.mine.bukkit.protection.WorldGuardAPI.getRegionSet(WorldGuardAPI.java:179) ~[?:?]
	at com.elmakers.mine.bukkit.protection.WorldGuardAPI.getWandPermission(WorldGuardAPI.java:240) ~[?:?]
	at com.elmakers.mine.bukkit.protection.WorldGuardManager.getWandPermission(WorldGuardManager.java:95) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.hasWandPermission(MagicController.java:3058) ~[?:?]
	at com.elmakers.mine.bukkit.wand.Wand.activate(Wand.java:4508) ~[?:?]
	at com.elmakers.mine.bukkit.wand.Wand.activate(Wand.java:4500) ~[?:?]
	at com.elmakers.mine.bukkit.magic.Mage.checkWand(Mage.java:1495) ~[?:?]
	at com.elmakers.mine.bukkit.magic.Mage.checkWand(Mage.java:1510) ~[?:?]
	at com.elmakers.mine.bukkit.magic.CheckWandTask.run(CheckWandTask.java:19) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-429]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.2.jar:git-Paper-429]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 16 more
```

**Comment by NathanWolf** [comment]
Well, that sucks.

**Comment by killme** [comment]
Who needs ABI compatibility anyways

**Comment by NathanWolf** [comment]
Definitely not those guys. And if you go ask about it in IRC they'll tell you to f off.

**Comment by mibby** [comment]
🤷‍♂️ ItemJoin added a check to see what version of WorldEdit players are using for Vector matching if it helps as a reference.

**Comment by mibby** [comment]
@NathanWolf Would it be possible to get a dev build with the breaking vector changes implemented? :(

**Comment by NathanWolf** [comment]
The latest dev build should work with latest WE/WG:

http://jenkins.elmakers.com/job/MagicPlugin/2816/com.elmakers.mine.bukkit.plugins$Magic/
