### ISSUE TITLE
Players Unable to Progress

### ISSUE THREAD

**Issue by brodiegeek** [elBukkit/MagicPlugin#438]
Players _(including myself)_ on my server can reach a certain level and will be stuck there. Once all the spells for a current level are purchased, it will give the **_You have progressed to student_** message, and the particles will explode everywhere, but nothing happens after this. The wand remains the same (beginner) and any further attempts to progress will just cause the message again and give the particles again.

**Comment by brodiegeek** [comment]
Here is the error by the way:
`[Magic] Spell cast failed for spellshop
org.bukkit.command.CommandException: Unhandled exception executing command 'broadcast' in plugin essentialsplusplus v3.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-6b015b4-94b8708]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-6b015b4-94b8708]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:696) ~[spigot.jar:git-Spigot-6b015b4-94b8708]
	at com.elmakers.mine.bukkit.wand.WandUpgradePath.upgraded(WandUpgradePath.java:563) ~[?:?]
	at com.elmakers.mine.bukkit.wand.WandUpgradePath.upgrade(WandUpgradePath.java:737) ~[?:?]
	at com.elmakers.mine.bukkit.action.builtin.UpgradePathAction.perform(UpgradePathAction.java:44) ~[?:?]
	at com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:38) ~[?:?]
	at com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:226) ~[?:?]
	at com.elmakers.mine.bukkit.action.ActionHandler.start(ActionHandler.java:167) ~[?:?]
	at com.elmakers.mine.bukkit.spell.ActionSpell.onCast(ActionSpell.java:140) ~[?:?]
	at com.elmakers.mine.bukkit.spell.BaseSpell.finalizeCast(BaseSpell.java:1465) ~[?:?]
	at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1330) ~[?:?]
	at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1335) ~[?:?]
	at com.elmakers.mine.bukkit.action.builtin.SelectorAction$SelectorOption.give(SelectorAction.java:779) ~[?:?]
	at com.elmakers.mine.bukkit.action.builtin.SelectorAction.clicked(SelectorAction.java:997) ~[?:?]
	at com.elmakers.mine.bukkit.magic.listener.InventoryController.onInventoryClick(InventoryController.java:147) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot.jar:git-Spigot-6b015b4-94b8708]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-6b015b4-94b8708]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot.jar:git-Spigot-6b015b4-94b8708]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot.jar:git-Spigot-6b015b4-94b8708]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2140) ~[spigot.jar:git-Spigot-6b015b4-94b8708]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot.jar:git-Spigot-6b015b4-94b8708]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Spigot-6b015b4-94b8708]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-6b015b4-94b8708]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-6b015b4-94b8708]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-6b015b4-94b8708]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot.jar:git-Spigot-6b015b4-94b8708]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-6b015b4-94b8708]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-6b015b4-94b8708]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.command.ColouredConsoleSender cannot be cast to org.bukkit.entity.Player
	at me.damian.essentialsplusplus.Core.onCommand(Core.java:90) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-6b015b4-94b8708]
	... 34 more`

**Comment by brodiegeek** [comment]
**_For anyone who has this issue,_**

### DISABLE ESSENTIALS + +

**Comment by NathanWolf** [comment]
Alternately, change the upgrade commands via paths.yml to remove the broadcast.

It's kind of lame that /broadcast is so broken in that plugin, though.
