### ISSUE TITLE
NoSuchMethodException: org.bukkit.craftbukkit.v1_13_R2.CraftWorld.getTileEntityAt

### ISSUE THREAD

**Issue by mibby** [elBukkit/MagicPlugin#457]
Paper dev 488 (Spigot 1.13.2)
Magic dev 2829

@NathanWolf 

```
[04:51:15] [Server thread/INFO]: [Magic] Enabling Magic v7.6.19-SNAPSHOT-95e99a0
[04:51:15] [Server thread/WARN]: An error occurred, handling of tile entities may not work well
java.lang.NoSuchMethodException: org.bukkit.craftbukkit.v1_13_R2.CraftWorld.getTileEntityAt(int, int, int)
	at java.lang.Class.getMethod(Class.java:2109) ~[?:?]
	at com.elmakers.mine.bukkit.utility.NMSUtils.initialize(NMSUtils.java:906) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicPlugin.onEnable(MagicPlugin.java:171) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by mibby** [comment]
This is how NBTEditor resolved the issue.
https://github.com/goncalomb/NBTEditor/commit/bb16ca09535e0fdc015af20b3065b56c28a42f2c

**Comment by mibby** [comment]
Seems all good now, thanks!
