### ISSUE TITLE
CommandException: Unhandled exception during tab completion for command

### ISSUE THREAD

**Issue by mibby** [elBukkit/MagicPlugin#484]
Paper dev 570
Magic dev 2854

```
[22:02:53] [Netty Epoll Server IO #2/ERROR]: Exception when mibby attempted to tab complete mgive wand_chainlightning
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/mgive wand_chainlightning' in plugin Magic v7.6.20-SNAPSHOT-f33cb09
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[patched_1.13.2.jar:git-Paper-570]
	at org.bukkit.command.Command.tabComplete(Command.java:95) ~[patched_1.13.2.jar:git-Paper-570]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:232) ~[patched_1.13.2.jar:git-Paper-570]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.tabCompleteCommand(CraftServer.java:1775) ~[patched_1.13.2.jar:git-Paper-570]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.tabComplete(CraftServer.java:1747) ~[patched_1.13.2.jar:git-Paper-570]
	at org.bukkit.craftbukkit.v1_13_R2.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[patched_1.13.2.jar:git-Paper-570]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:68) ~[patched_1.13.2.jar:git-Paper-570]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:379) ~[patched_1.13.2.jar:git-Paper-570]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:549) ~[patched_1.13.2.jar:git-Paper-570]
	at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:36) ~[patched_1.13.2.jar:git-Paper-570]
	at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-570]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:156) ~[patched_1.13.2.jar:git-Paper-570]
	at net.minecraft.server.v1_13_R2.NetworkManager.channelRead0(NetworkManager.java:145) ~[patched_1.13.2.jar:git-Paper-570]
	at net.minecraft.server.v1_13_R2.NetworkManager.channelRead0(NetworkManager.java:31) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[patched_1.13.2.jar:git-Paper-570]
	at me.neznamy.tab.bukkit.packets.Packet$1.channelRead(Packet.java:56) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-570]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[patched_1.13.2.jar:git-Paper-570]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.13.2.jar:git-Paper-570]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]
	at java.util.HashMap$ValueIterator.next(HashMap.java:1521) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.getSpellTemplates(MagicController.java:4118) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicPlugin.getSpellTemplates(MagicPlugin.java:483) ~[?:?]
	at com.elmakers.mine.bukkit.magic.command.MagicGiveCommandExecutor.onTabComplete(MagicGiveCommandExecutor.java:138) ~[?:?]
	at com.elmakers.mine.bukkit.magic.command.MagicTabExecutor.onTabComplete(MagicTabExecutor.java:57) ~[?:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:138) ~[patched_1.13.2.jar:git-Paper-570]
	... 57 more
```

**Comment by NathanWolf** [comment]
Honestly no idea on this one :(

Do you have any steps to reproduce this? I tried various forms of tab-completing an `/mgive <wand>` command but could not get an error.

**Comment by NathanWolf** [comment]
Closing this, but if you're still seeing it please let me know.
