### ISSUE TITLE
Config Errors

### ISSUE THREAD

**Issue by BZEagle** [elBukkit/MagicPlugin#537]
The plugin shows a lot of errors after server restarting.But I haven't changed the config.I need some help.
`[22:11:26 WARN]: [Magic]  Error loading messages
org.bukkit.configuration.InvalidConfigurationException: unacceptable code point '' (0x9C) special characters are not allowed
in "'string'", position 861
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:163) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:131) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at com.elmakers.mine.bukkit.utility.CompatibilityUtils.loadConfiguration(CompatibilityUtils.java:635) ~[?:?]
        at com.elmakers.mine.bukkit.magic.ConfigurationLoadTask.loadConfigFolder(ConfigurationLoadTask.java:373) ~[?:?]
        at com.elmakers.mine.bukkit.magic.ConfigurationLoadTask.loadConfigFile(ConfigurationLoadTask.java:298) ~[?:?]
        at com.elmakers.mine.bukkit.magic.ConfigurationLoadTask.run(ConfigurationLoadTask.java:543) ~[?:?]
        at com.elmakers.mine.bukkit.magic.ConfigurationLoadTask.runNow(ConfigurationLoadTask.java:582) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:1722) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:1714) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicPlugin.reload(MagicPlugin.java:258) ~[?:?]
        at com.elmakers.mine.bukkit.magic.command.MagicCommandExecutor.onCommand(MagicCommandExecutor.java:126) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:696) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:483) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:211) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:136) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanPlain(ScannerImpl.java:1999) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchPlain(ScannerImpl.java:1044) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:399) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:586) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:124) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[EagleCraft.jar:git-Paper-"fb25dc17"]
        ... 20 more
[22:11:26 INFO]: [Magic]  Using compatibility configs: examples/1.13/spells.yml
[22:11:27 INFO]: An error occurred reloading configurations, please check server logs!
[22:11:27 WARN]: [Magic]  *** An error occurred while loading configurations ***
[22:11:27 WARN]: [Magic]  ***         Magic is temporarily disabled          ***
[22:11:27 WARN]: [Magic]  ***   Please check the errors above, fix configs   ***
[22:11:27 WARN]: [Magic]  ***    And '/magic load' or restart the server     ***`
And I couldn't find the character "".The character looks like "oe".
![image](https://user-images.githubusercontent.com/47891648/61172871-9b097100-a5bd-11e9-880e-ac9dba58caa8.png)

**Comment by NathanWolf** [comment]
Have you tried shutting down the server and deleting all of the yml files in plugins/Magic ?

**Comment by killme** [comment]
Also, make sure the file is stored as UTF-8

**Comment by NathanWolf** [comment]
Please re-open if you're still having config issues.
