### ISSUE TITLE
Broomsticks Stopping Server

### ISSUE THREAD

**Issue by 4evswhovian** [elBukkit/MagicPlugin#538]
Hello,
I have been really enjoying this plugin and find it incredible, however, when I try to use the broomsticks I fly a few blocks and then the server stops. It's so frustrating, three times it has happened and it only happens when using the broomstick. I really want to continue use of this plugin but if it is going to keep crashing I might remove it from my server.

This is what pops up in the console 

[17:14:12] [Server thread/WARN]: 4EvsWhovian moved too quickly! 10.073309782774686,0.0,-0.7092506151238922
[17:14:13] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.AssertionError: TRAP
        at net.minecraft.server.v1_14_R1.ItemStack.checkEmpty(ItemStack.java:82) ~[craftbukkit.jar:git-Bukkit-2349feb]
        at net.minecraft.server.v1_14_R1.ItemStack.setCount(ItemStack.java:851) ~[craftbukkit.jar:git-Bukkit-2349feb]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:397) ~[craftbukkit.jar:git-Bukkit-2349feb]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1285) ~[craftbukkit.jar:git-Bukkit-2349feb]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(SourceFile:32) ~[craftbukkit.jar:git-Bukkit-2349feb]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(SourceFile:9) ~[craftbukkit.jar:git-Bukkit-2349feb]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[craftbukkit.jar:git-Bukkit-2349feb]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[craftbukkit.jar:git-Bukkit-2349feb]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) ~[craftbukkit.jar:git-Bukkit-2349feb]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[craftbukkit.jar:git-Bukkit-2349feb]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) ~[craftbukkit.jar:git-Bukkit-2349feb]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:856) ~[craftbukkit.jar:git-Bukkit-2349feb]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:849) ~[craftbukkit.jar:git-Bukkit-2349feb]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) ~[craftbukkit.jar:git-Bukkit-2349feb]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:832) ~[craftbukkit.jar:git-Bukkit-2349feb]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:773) [craftbukkit.jar:git-Bukkit-2349feb]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

Then the server stops

**Comment by NathanWolf** [comment]
You can't use brooms in creative mode. It's a spigot bug, as far as I can tell.

**Comment by 4evswhovian** [comment]
> You can't use brooms in creative mode. It's a spigot bug, as far as I can tell.

Thank you so much, it does work in survival. I'm very glad I can continue to use this plugin.
