### ISSUE TITLE
Using air for hat/wear action

### ISSUE THREAD

**Issue by NeoFalcon1605** [elBukkit/MagicPlugin#565]
I tried to cast gills using "/cast gills item air" on 1.14.4 with magic version 7.7.4 and got the following error in the console:

[15:26:40] [Server thread/WARN]: [Magic]  Spell cast failed for gills
java.lang.NullPointerException: null
        at com.elmakers.mine.bukkit.action.builtin.WearAction.perform(WearAction.java:210) ~[?:?]
        at com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:38) ~[?:?]
        at com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:225) ~[?:?]
        at com.elmakers.mine.bukkit.action.ActionHandler.start(ActionHandler.java:166) ~[?:?]
        at com.elmakers.mine.bukkit.spell.ActionSpell.onCast(ActionSpell.java:141) ~[?:?]
        at com.elmakers.mine.bukkit.spell.BaseSpell.finalizeCast(BaseSpell.java:1465) ~[?:?]
        at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1330) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicController.cast(MagicController.java:3474) ~[?:?]
        at com.elmakers.mine.bukkit.magic.MagicPlugin.cast(MagicPlugin.java:468) ~[?:?]
        at com.elmakers.mine.bukkit.magic.command.CastCommandExecutor.processCastCommand(CastCommandExecutor.java:166) ~[?:?]
        at com.elmakers.mine.bukkit.magic.command.CastCommandExecutor.onCommand(CastCommandExecutor.java:146) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-1ec1b05]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by NeoFalcon1605** [comment]
Oh, I was hoping for wear to be able to temporarily remove armour, does there happen to be another action that would work for this?

**Comment by NathanWolf** [comment]
Is this working for you?

**Comment by NeoFalcon1605** [comment]
It doesn't give any errors, but it also doesn't equip air for  the wear action.

**Comment by NathanWolf** [comment]
Hm, I thought I had fixed this, sorry. Do you have a simple spell example you could share to help me figure it out?

**Comment by NathanWolf** [comment]
Thanks!

But yeah... ok so unfortunately this is not going to work.

I forgot how Wear works, it needs to set some metadata on the item to remember the item that was previously there. This makes sure that the player's original armor isn't lost, even in the event of a server crash or restart.

But unfortunately you can not put metadata on air.

I think the best solution is to make an invisible item- that's something I think I could add to the resource pack pretty easily.

**Comment by NeoFalcon1605** [comment]
Thank you, yeah it is okay

**Comment by NathanWolf** [comment]
Released in 7.7.5
