### ISSUE TITLE
Towny Integration Broken

### ISSUE THREAD

**Issue by alekso56** [elBukkit/MagicPlugin#573]
Using latest towny Towny Advanced 0.94.0.0 [CB/Spigot 1.13] 
```
java.lang.NoSuchMethodError: com.palmergames.bukkit.towny.utils.PlayerCacheUtil.getCachePermission(Lorg/bukkit/entity/Player;Lorg/bukkit/Location;Ljava/lang/Integer;BLcom/palmergames/bukkit/towny/object/TownyPermission$ActionType;)Z
	at com.elmakers.mine.bukkit.protection.TownyAPI.hasBuildPermission(TownyAPI.java:97) ~[?:?]
	at com.elmakers.mine.bukkit.protection.TownyManager.hasBuildPermission(TownyManager.java:63) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.hasBuildPermission(MagicController.java:697) ~[?:?]
	at com.elmakers.mine.bukkit.magic.Mage.hasBuildPermission(Mage.java:2307) ~[?:?]
	at com.elmakers.mine.bukkit.spell.BaseSpell.hasBuildPermission(BaseSpell.java:1436) ~[?:?]
	at com.elmakers.mine.bukkit.spell.BaseSpell.canCast(BaseSpell.java:1375) ~[?:?]
	at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1212) ~[?:?]
	at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1098) ~[?:?]
	at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1340) ~[?:?]
	at com.elmakers.mine.bukkit.wand.Wand.cast(Wand.java:4133) ~[?:?]
	at com.elmakers.mine.bukkit.wand.Wand.cast(Wand.java:4093) ~[?:?]
	at com.elmakers.mine.bukkit.wand.Wand.performAction(Wand.java:5513) ~[?:?]
	at com.elmakers.mine.bukkit.magic.listener.PlayerController.onPlayerAnimate(PlayerController.java:426) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor962.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-639]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.13.2.jar:git-Paper-639]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-639]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1825) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.PacketPlayInArmAnimation.a(SourceFile:32) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.PacketPlayInArmAnimation.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-639]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_211]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-639]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
```

**Comment by NathanWolf** [comment]
Towny updated their API, breaking the old version, but still doesn't have an API available via Maven.

I probably won't fix this until they get a maven repo up. I'll try and check back later, but for now I would consider Magic/Towny integration broken. Sorry!

**Comment by alekso56** [comment]
Towny added their api to a new maven repo, https://github.com/TownyAdvanced/Towny/wiki/TownyAPI#getting-started-with-towny-and-your-ide

**Comment by NathanWolf** [comment]
Well unfortunately github's Maven hosting requires authentication, which is a little lame. I can't expect everyone integrating with Magic to set up their Maven info .... anyway, I installed the latest jar manually into my own repo.

I've updated the integration but haven't tested it. If you want to try it out, please let me know if it works.

http://jenkins.elmakers.com/job/MagicPlugin/2926/

**Comment by killme** [comment]
ee5f66c9c9bdcc8a46ce208427e0742135d0ace8
