### ISSUE TITLE
Unable to damage dragon

### ISSUE THREAD

**Issue by NeoFalcon1605** [elBukkit/MagicPlugin#599]
I've tried on 1.14.4 and 1.12.2 using magic version 7.7.5 to damage the dragon and overall spells using magic damage have not damaged the dragon, and I tested this using laser and superkill.

On further testing, using "/cast laser damage_type physical" on 1.12.2 would damage the dragon while on 1.14.4 it would not.  The spells were targeting the dragon (fury would target the different parts of the dragon with each missile) but not damaging it.

With more testing on 1.14.4 I found an issue with out of world damage which provided the following errors: 
```
[15:07:30] [Server thread/INFO]: NeoFalcon issued server command: /cast missile|4 damage_type out_of_world
[15:07:30] [Server thread/WARN]: java.lang.IllegalArgumentException: java.lang.ClassCastException@4cce61a6
[15:07:30] [Server thread/WARN]:        at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
[15:07:30] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:07:30] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[15:07:30] [Server thread/WARN]:        at com.elmakers.mine.bukkit.utility.CompatibilityUtils.damage(CompatibilityUtils.java:537)
[15:07:30] [Server thread/WARN]:        at com.elmakers.mine.bukkit.action.builtin.DamageAction.perform(DamageAction.java:141)
[15:07:30] [Server thread/WARN]:        at com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:38)
[15:07:30] [Server thread/WARN]:        at com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:225)
[15:07:30] [Server thread/WARN]:        at com.elmakers.mine.bukkit.action.CompoundAction.perform(CompoundAction.java:105)
[15:07:30] [Server thread/WARN]:        at com.elmakers.mine.bukkit.action.ActionContext.perform(ActionContext.java:38)
[15:07:30] [Server thread/WARN]:        at com.elmakers.mine.bukkit.action.ActionHandler.perform(ActionHandler.java:225)
[15:07:30] [Server thread/WARN]:        at com.elmakers.mine.bukkit.batch.ActionBatch.process(ActionBatch.java:38)
[15:07:30] [Server thread/WARN]:        at com.elmakers.mine.bukkit.magic.Mage.processPendingBatches(Mage.java:1700)
[15:07:30] [Server thread/WARN]:        at com.elmakers.mine.bukkit.magic.MagicController.processPendingBatches(MagicController.java:1296)
[15:07:30] [Server thread/WARN]:        at com.elmakers.mine.bukkit.magic.BatchUpdateTask.run(BatchUpdateTask.java:12)
[15:07:30] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
[15:07:30] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
[15:07:30] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022)
[15:07:30] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393)
[15:07:30] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970)
[15:07:30] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815)
[15:07:30] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
```

I then tested all the damage types using missile|4 with the following results:
- anvil: Same error as out of world
- burn: Same error as out of world
- cactus: Same error as out of world
- cramming: Same error as out of world
- dragon_breath:  Same error as out of world
- drown: Same error as out of world
- explosion: No error, no damage dealt
- fall:  No error, no damage dealt
- falling_block: Same error as out of world
- fire: No error, no damage dealt
- fly_into_wall: Same error as out of world
- generic: Same error as out of world
- hot_floor: Same error as out of world
- lava: Same error as out of world
- lightning: Same error as out of world
- magic: No error, no damage dealt
- out_of_world: N/A
- overall: No error, no damage dealt
- physical: No error, no damage dealt
- projectile: No error, no damage dealt
- starve: Same error as out of world
- stuck: Same error as out of world
- wither: Same error as out of world
- custom damage type: No error, no damage dealt

**Comment by NathanWolf** [comment]
Wow, thanks for digging into this so hard!

So for whatever reason it has always required a weird hack to damage the ender dragon. Just calling Entity.damage has never worked right.

So I have an NMS hack to apply "thorns" damage, which seems to be the only damage type that works against the ender dragon. I have no idea why that is.

But that NMS method has been broken since 1.13, apparently. I think I have a fix ready, will push it to a dev build once I've tested it.

**Comment by killme** [comment]
17a60829db36d2ce73b6cfe918d9cf29eba37879
