### ISSUE TITLE
Magic 1.15 error

### ISSUE THREAD

**Issue by mpdk** [elBukkit/MagicPlugin#618]
I know it's new, but in case you haven't tried yourself, here is something from the log and how it fails

[11:12:24] [Server thread/INFO]: [Magic] Loading Magic v7.7.6-748b664
[11:12:25] [Server thread/INFO]: [Magic] Found WorldGuard 7+
[11:12:25] [Server thread/INFO]: [Magic] Pre-check for WorldGuard custom flag registration
[11:12:25] [Server thread/INFO]: [Magic] Registered custom WorldGuard flags: allowed-spells, blocked-spells, allowed-spell-categories, blocked-spell-categories, allowed-wands, blocked-wands, spell-overrides, destructible, reflective, spawn-tags

[11:12:52] [Server thread/ERROR]: An unexpected error occurred initializing Magic
java.lang.NoSuchMethodException: net.minecraft.server.v1_15_R1.NBTTagString.<init>(java.lang.String)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_231]
	at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_231]
	at com.elmakers.mine.bukkit.utility.NMSUtils.initialize(NMSUtils.java:501) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicPlugin.onEnable(MagicPlugin.java:171) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.jar:git-Paper-8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.jar:git-Paper-8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.jar:git-Paper-8]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.jar:git-Paper-8]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.jar:git-Paper-8]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.jar:git-Paper-8]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.jar:git-Paper-8]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.jar:git-Paper-8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
[11:12:52] [Server thread/INFO]: [Magic] Something went wrong with some Deep Magic, plugin will not load.
[11:12:52] [Server thread/INFO]: [Magic] Please make sure you are running a compatible version of Spigot (1.9 or Higher)!

**Comment by NathanWolf** [comment]
I just checked the other day, is there an official (not Paper) build available for 1.15?

That error looks... bad. Like they may have changed some basic NBT functionality :(

**Comment by NathanWolf** [comment]
Added 1.15 support in 7.8

There is something weird with the RP icons but I can hopefully fix that after the fact.
