### ISSUE TITLE
Permissions Bug?

### ISSUE THREAD

**Issue by marvinej** [elBukkit/MagicPlugin#648]
Players unable to cast fire or fireball.

![](https://cdn.discordapp.com/attachments/580101207364861954/680630426158497792/unknown.png)
![](https://cdn.discordapp.com/attachments/580101207364861954/680630634431250450/unknown.png)
![](https://cdn.discordapp.com/attachments/580101207364861954/680633211742978070/unknown.png)
![](https://cdn.discordapp.com/attachments/580101207364861954/680636455059718194/unknown.png)

**Comment by NathanWolf** [comment]
That is usually caused by pvp or build permissions (WorldGuard, Factions, Towny, etc)

**Comment by marvinej** [comment]
will these spells bypass worldguard or grief prevention if i allow them? why are they blocked?

**Comment by marvinej** [comment]
@NathanWolf This error shows in console when the player tries to cast it.
```
[02:14:16 WARN]: java.lang.IllegalArgumentException: java.lang.ClassCastException@6a4cb45b
[02:14:16 WARN]:        at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
[02:14:16 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:14:16 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[02:14:16 WARN]:        at com.elmakers.mine.bukkit.utility.NMSUtils.containsNode(NMSUtils.java:1656)
[02:14:16 WARN]:        at com.elmakers.mine.bukkit.wand.Wand.isQuickCastSkill(Wand.java:2824)
[02:14:16 WARN]:        at com.elmakers.mine.bukkit.magic.listener.PlayerController.onPlayerEquip(PlayerController.java:138)
[02:14:16 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor585.execute(Unknown Source)
[02:14:16 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[02:14:16 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[02:14:16 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:14:16 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559)
[02:14:16 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1560)
[02:14:16 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInHeldItemSlot.a(SourceFile:30)
[02:14:16 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInHeldItemSlot.a(SourceFile:8)
[02:14:16 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[02:14:16 WARN]:        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[02:14:16 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[02:14:16 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[02:14:16 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[02:14:16 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038)
[02:14:16 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031)
[02:14:16 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[02:14:16 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015)
[02:14:16 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938)
[02:14:16 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by marvinej** [comment]
the fire spell works in pvp zones only as designated by worldguard if i set

# Enable worldguard protection against construction spells, and PVP
region_manager_enabled: false

but that also allows them to break protected blocks with magic missile.

when it is set to true it prevents the fire spell from being used regardless of where you are.

**Comment by NathanWolf** [comment]
Explosive spells are disabled in no-pvp regions because they can hurt other players with splash damage.

If you want to enable specific spells add this to your spells.yml

```
fireball:
  parameters:
    bypass_pvp: true
```

**Comment by marvinej** [comment]
why does enabling world guard integration cause it not to read the worldguard pvp flag correctly?

**Comment by NathanWolf** [comment]
I don’t know what you mean. The pvp flag disables the fire spell, otherwise players can damage each other with it. Worldguard won’t prevent it, as it is indirect damage and not really pvp.

**Comment by marvinej** [comment]
Perhaps i didn't explain this very well. The configuration `region_manager_enabled:` when set to true it works to stop players from damaging areas with spells like magic missle. But also when set to true players can not use pvp spells when they are standing within a worldguard region that has pvp set to allow. I am suggesting that this is most likely not working as intended.

**Comment by NathanWolf** [comment]
Some spells like fire and fireball are also not allowed because they can break blocks, regardless of the pvp settings.

Pvp, build and break permissions can all be bypassed via spell parameters if you wish to customize any of this.

If in doubt about what is preventing a spell cast, try using the “/mage check” command with that spell equipped.

**Comment by marvinej** [comment]
I tried adding this to spells.yml as i am having an issue with players being able to bypass grief prevention and steal animals.
```
Pull:
  parameters:
    require_build: true
    require_break: true
Push:
  parameters:
    require_build: true
    require_break: true
```
It still returns pull requires build: false
and pull requires break: false

**Comment by NathanWolf** [comment]
Try lowercase p push and pull

**Comment by marvinej** [comment]
that's how i had it at first. I changed it during testing. Same result.

**Comment by NathanWolf** [comment]
Hm, ok sorry I’m not at my computer but it is definitely lowercase, I can’t remember if the require_ properties go on parameters or not.

Please try them at the top level. If that doesn’t work I’ll try it out myself when I get a chance.

‘’’
push:
  require_build: true
‘’’

**Comment by NathanWolf** [comment]
Oh and also make sure you’re not opped when testing

**Comment by marvinej** [comment]
ah, removing the parameters line fixed the issue. This should protect the animals a little bit better however now even when they are trusted on the grief prevention claim they still can not use it.

**Comment by marvinej** [comment]
I own a separate test account so it never has admin or op permissions

**Comment by marvinej** [comment]
i still think this is an actual bug if you have some free time at some point we could schedule to look at it together.

**Comment by NathanWolf** [comment]
That probably won't be possible, sorry - so the problem is that trusted users can't cast the restricted spells?

Can they place blocks?

The check is basically just a call to griefprevention's API so if it's not working properly with trusted players there may not be anything I can do about it.

```
    public boolean hasBuildPermission(Player player, Block block) {
        if (block != null && griefPrevention != null) {
            Claim claim = griefPrevention.dataStore.getClaimAt(block.getLocation(), false, null);
            if (claim != null) {
                return claim.allowEdit(player) == null;
            }
        }
        return true;
    }
```

**Comment by NathanWolf** [comment]
Sorry this fell through the cracks. Please re-open if you're still having trouble.
