### ISSUE TITLE
Could not pass event InventoryClickEvent - java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mibby** [elBukkit/MagicPlugin#721]
Magic dev 3107
Tuinity dev 317 (Paper Spigot 1.16.1)
```
[08:29:26] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Magic v7.9.11-SNAPSHOT-87e46d2
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 36
	at java.util.Arrays$ArrayList.get(Arrays.java:4164) ~[?:?]
	at net.minecraft.server.v1_16_R1.NonNullList.get(SourceFile:46) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at net.minecraft.server.v1_16_R1.PlayerInventory.getItem(PlayerInventory.java:541) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftInventory.getItem(CraftInventory.java:49) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at com.elmakers.mine.bukkit.magic.listener.InventoryController.onInventoryClick(InventoryController.java:326) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor725.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2438) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1191) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1184) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1160) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Tuinity-"f265b38"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by NathanWolf** [comment]
Hm strange- that's this code here:
`ItemStack destinationItem = player.getInventory().getItem(event.getHotbarButton());`

which should only get triggered on hotbar_swap or hotbar_move_and_readd ... I'll put in a special check for this being -1 but that seems like an odd thing for the API to be doing.
