### ISSUE TITLE
Double-Adding Entities on Undo (Item Frames)

### ISSUE THREAD

**Issue by Volgeop** [elBukkit/MagicPlugin#729]
Hi, I got error in console, don't know why it appeared, but it isn't first time. https://pastebin.com/Ucn3SLZh
```
[14:37:43] [Server thread/ERROR]: Attempted Double World add on EntityItemFrame['Item Frame'/49693, uuid='a8cbdc03-858c-4d81-9d40-f68d1074ce66', l='ServerLevel[world]', x=1006.50, y=70.50, z=-111.97, cx=62, cz=-7, tl=0, v=true, d=false]
java.lang.Throwable: null
	at net.minecraft.server.v1_16_R1.WorldServer.addEntity0(WorldServer.java:1128) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.WorldServer.addEntity(WorldServer.java:1061) ~[patched_1.16.1.jar:git-Paper-131]
	at jdk.internal.reflect.GeneratedMethodAccessor160.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at com.elmakers.mine.bukkit.utility.CompatibilityUtils.addToWorld(CompatibilityUtils.java:439) ~[?:?]
	at com.elmakers.mine.bukkit.entity.EntityData.trySpawn(EntityData.java:604) ~[?:?]
	at com.elmakers.mine.bukkit.entity.EntityData.undo(EntityData.java:665) ~[?:?]
	at com.elmakers.mine.bukkit.block.UndoList.undoEntityEffects(UndoList.java:579) ~[?:?]
	at com.elmakers.mine.bukkit.batch.UndoBatch.finish(UndoBatch.java:102) ~[?:?]
	at com.elmakers.mine.bukkit.batch.UndoBatch.process(UndoBatch.java:91) ~[?:?]
	at com.elmakers.mine.bukkit.magic.Mage.processPendingBatches(Mage.java:1851) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.processPendingBatches(MagicController.java:1348) ~[?:?]
	at com.elmakers.mine.bukkit.magic.BatchUpdateTask.run(BatchUpdateTask.java:12) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by NathanWolf** [comment]
Not going to have a solution for this one anytime soon, but it should be a benign error.

**Comment by NathanWolf** [comment]
This should be fixed in the latest release. Thanks!
