### ISSUE TITLE
Division by 0

### ISSUE THREAD

**Issue by Elsopeen** [elBukkit/MagicPlugin#76]
Hello, 
I have just update the plugin on my server to the latest build, and my players and I cannot cast any spell anymore. I'll check if something has changed in the default configurations, but when anyone cast any spell, we get that error :
[20:29:08 ERROR]: Could not pass event PlayerInteractEvent to Magic v6.1-SNAPSHOT
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1388) [minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
at net.minecraft.server.v1_9_R1.PacketPlayInArmAnimation.a(SourceFile:32) [minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
at net.minecraft.server.v1_9_R1.PacketPlayInArmAnimation.a(SourceFile:9) [minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.ArithmeticException: / by zero
at com.elmakers.mine.bukkit.spell.BaseSpell.getProgressLevel(BaseSpell.java:1098) ~[?:?]
at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1088) ~[?:?]
at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:916) ~[?:?]
at com.elmakers.mine.bukkit.spell.BaseSpell.cast(BaseSpell.java:1673) ~[?:?]
at com.elmakers.mine.bukkit.wand.Wand.cast(Wand.java:3687) ~[?:?]
at com.elmakers.mine.bukkit.wand.Wand.cast(Wand.java:3669) ~[?:?]
at com.elmakers.mine.bukkit.wand.Wand.performAction(Wand.java:4865) ~[?:?]
at com.elmakers.mine.bukkit.magic.listener.PlayerController.onPlayerInteract(PlayerController.java:431) ~[?:?]
at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_openmod.jar:git-Spigot-a1b8bf3-f01861f]
... 18 more
I hope you will be able to fix this major problem, we cannot really play without (y)our magic, it is a major part of our server (even if we aren't so much).
Waiting for your answer,
Best regards,
Elsopeen

**Comment by dumptruckman** [comment]
That was my fault. Sorry about that. It's fixed now. New build here http://jenkins.elmakers.com/job/MagicPlugin/1562/

**Comment by NathanWolf** [comment]
Thanks for the fix!

Using dev builds is always a risky proposition! :)
