### ISSUE TITLE
Error restoring entity type DROPPED_ITEM

### ISSUE THREAD

**Issue by alekso56** [elBukkit/MagicPlugin#767]
magic 7.11
```
[Server thread/WARN]: Error restoring entity type DROPPED_ITEM at Location{world=CraftWorld{name=world},x=1,y=71.0,z=1,pitch=0.0,yaw=291.9712}
java.lang.IllegalArgumentException: Cannot drop air
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.EntityItem.setItemStack(EntityItem.java:454) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.EntityItem.<init>(EntityItem.java:42) ~[patched_1.16.3.jar:git-Paper-251]
	at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.dropItem(CraftWorld.java:748) ~[patched_1.16.3.jar:git-Paper-251]
	at com.elmakers.mine.bukkit.entity.EntityData.trySpawn(EntityData.java:652) ~[?:?]
	at com.elmakers.mine.bukkit.entity.EntityData.undo(EntityData.java:748) ~[?:?]
	at com.elmakers.mine.bukkit.block.UndoList.undoEntityEffects(UndoList.java:580) ~[?:?]
	at com.elmakers.mine.bukkit.batch.UndoBatch.finish(UndoBatch.java:119) ~[?:?]
	at com.elmakers.mine.bukkit.batch.UndoBatch.process(UndoBatch.java:103) ~[?:?]
	at com.elmakers.mine.bukkit.batch.UndoBatch.complete(UndoBatch.java:153) ~[?:?]
	at com.elmakers.mine.bukkit.magic.listener.BlockController.undoPending(BlockController.java:376) ~[?:?]
	at com.elmakers.mine.bukkit.magic.listener.BlockController.onWorldSaveEvent(BlockController.java:406) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor909.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-251]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.3.jar:git-Paper-251]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-251]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.WorldServer.saveIncrementally(WorldServer.java:956) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1242) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
```

**Comment by NathanWolf** [comment]
Thank you. I do not know how or why this happens (why did it record a dropped air item in the first place?) but I do have a fix for this ready for the next release.
