### ISSUE TITLE
/wand list command fails

### ISSUE THREAD

**Issue by silentnyte** [elBukkit/MagicPlugin#789]
When using the /wand list command a java exception occurs.

Server version: Paper 1.16.4 build 277
(I know you are not supporting Paper but you might want to check if this is an issue in spigot)
Magic version: 8.0.1

```
> wand list
[15:04:21 INFO]: Total wands: 143
[15:04:21 INFO]: admin : The Shusher : For admins only
[15:04:21 INFO]: alphabetizer : The Alphabetizer : Alphabetizes your wand inve...
[15:04:21 INFO]: antihunger : Anti-Hunger Upgrade : Never go hungry again!
[15:04:21 INFO]: appearance_apprentice : Apprentice Wand Appearance : It has transformed!
[15:04:21 WARN]: Unexpected exception while parsing console command "wand list"
org.bukkit.command.CommandException: Unhandled exception executing command 'wand' in plugin Magic v8.0.1-f50d77f
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-277]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-277]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-277]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:764) ~[patched_1.16.4.jar:git-Paper-277]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.4.jar:git-Paper-277]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.4.jar:git-Paper-277]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-277]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-277]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-277]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at com.elmakers.mine.bukkit.magic.command.WandPaginator.describe(WandPaginator.java:52) ~[?:?]
        at com.elmakers.mine.bukkit.magic.command.WandPaginator.describe(WandPaginator.java:18) ~[?:?]
        at com.elmakers.mine.bukkit.magic.command.Paginator.showItems(Paginator.java:21) ~[?:?]
        at com.elmakers.mine.bukkit.magic.command.Paginator.list(Paginator.java:52) ~[?:?]
        at com.elmakers.mine.bukkit.magic.command.WandCommandExecutor.onWandList(WandCommandExecutor.java:528) ~[?:?]
        at com.elmakers.mine.bukkit.magic.command.WandCommandExecutor.onCommand(WandCommandExecutor.java:85) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-277]
        ... 9 more

```

**Comment by NathanWolf** [comment]
Oops, thanks this is fixed now.
