### ISSUE TITLE
IllegalArgumentException: Path cannot be null

### ISSUE THREAD

**Issue by mibby** [elBukkit/MagicPlugin#940]
MagicPlugin dev 3854

```
[23:48:31] [Server thread/INFO]: [Magic] Enabling Magic v9.5-SNAPSHOT-4019d73
[23:48:31] [Server thread/INFO]: [Magic] EffectLib initialized
[23:48:32] [Server thread/INFO]: [Magic] Loaded 0 attributes
[23:48:32] [Server thread/ERROR]: Error occurred while enabling Magic v9.5-SNAPSHOT-4019d73 (Is it up to date?)
java.lang.IllegalArgumentException: Path cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.17.1.jar:git-Purpur-1300]
	at org.bukkit.configuration.MemorySection.get(MemorySection.java:237) ~[patched_1.17.1.jar:git-Purpur-1300]
	at com.elmakers.mine.bukkit.configuration.TranslatingConfigurationSection.get(TranslatingConfigurationSection.java:118) ~[?:?]
	at com.elmakers.mine.bukkit.configuration.TranslatingConfigurationSection.getConfigurationSection(TranslatingConfigurationSection.java:233) ~[?:?]
	at com.elmakers.mine.bukkit.resourcepack.ResourcePackManager.load(ResourcePackManager.java:79) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.loadProperties(MagicController.java:7791) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.processConfigurations(MagicController.java:1942) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.finalizeLoad(MagicController.java:1810) ~[?:?]
	at com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.run(ConfigurationLoadTask.java:869) ~[?:?]
	at com.elmakers.mine.bukkit.tasks.ConfigurationLoadTask.runNow(ConfigurationLoadTask.java:891) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2442) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2419) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2415) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.loadConfiguration(MagicController.java:2407) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.load(MagicController.java:2481) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicController.initialize(MagicController.java:1502) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicPlugin.initialize(MagicPlugin.java:186) ~[?:?]
	at com.elmakers.mine.bukkit.magic.MagicPlugin.onEnable(MagicPlugin.java:180) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Purpur-1300]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1300]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1300]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527) ~[patched_1.17.1.jar:git-Purpur-1300]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441) ~[patched_1.17.1.jar:git-Purpur-1300]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Purpur-1300]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[patched_1.17.1.jar:git-Purpur-1300]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1300]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:48:32] [Server thread/INFO]: [Magic] Disabling Magic v9.5-SNAPSHOT-4019d73
```

**Comment by mibby** [comment]
Caused by commit https://github.com/elBukkit/MagicPlugin/commit/f1600e94459df2e0fa0547a543c274ccf609b4ab here https://github.com/elBukkit/MagicPlugin/commit/f1600e94459df2e0fa0547a543c274ccf609b4ab#diff-24c3d27ed59080b3cc56f2e714cbca046d99df6bdd7f2502787220073a0c9d91R79-R83 when

```
# This resource pack will automatically be used if none is defined in your server.properties
# Set this to "" if you have some other plugin or Bungee managing resource packs.
resource_pack: ""
```

is set?

Downgrading to dev 3841, Magic initializes fine without erroring.

**Comment by NathanWolf** [comment]
Oops, sorry about that! I think the issue would arise if you had `enable_resource_pack: false`

it should be fixed here: https://jenkins.elmakers.com/job/MagicPlugin/3855/
