### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by Poulpinounette** [elBukkit/MagicPlugin#960]
hi we have some bug and don't get how to do. its a bit random..

Server:  Paper version git-Paper-637 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Magic: Magic 8.7.1-813d9fc
RAM: 24GB 
6 Core (dedicated core.)

Maybe sometimes a spell don't get the cooldown and we can spam the spell 2 times and maybe its that..

The error, dupliate infinite & crash server :/
```

[00:54:43] [Craft Async Scheduler Management Thread/WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[00:54:43] [Craft Scheduler Thread - 5026/WARN]: [Magic] Plugin Magic v8.7.1-813d9fc generated an exception while executing task 4795763
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.lang.Thread.start0(Native Method) ~[?:?]
	at java.lang.Thread.start(Thread.java:803) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:937) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1343) ~[?:?]
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:687) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncScheduler.cancelTask(CraftAsyncScheduler.java:56) ~[patched_1.16.5.jar:git-Paper-637]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.cancelTask(CraftScheduler.java:263) ~[patched_1.16.5.jar:git-Paper-637]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.cancel(CraftTask.java:142) ~[patched_1.16.5.jar:git-Paper-637]
	at com.elmakers.mine.bukkit.slikey.effectlib.EffectManager.removeEffect(EffectManager.java:282) ~[?:?]
	at com.elmakers.mine.bukkit.slikey.effectlib.EffectManager.done(EffectManager.java:274) ~[?:?]
	at com.elmakers.mine.bukkit.slikey.effectlib.Effect.done(Effect.java:461) ~[?:?]
	at com.elmakers.mine.bukkit.slikey.effectlib.Effect.run(Effect.java:287) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-637]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-637]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-637]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[00:54:43] [Craft Async Scheduler Management Thread/WARN]: 	at java.base/java.lang.Thread.start0(Native Method)
[00:54:43] [Craft Async Scheduler Management Thread/WARN]: 	at java.base/java.lang.Thread.start(Thread.java:803)
[00:54:43] [Craft Async Scheduler Management Thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:937)
[00:54:43] [Craft Async Scheduler Management Thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1005)
[00:54:43] [Craft Async Scheduler Management Thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[00:54:43] [Craft Async Scheduler Management Thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[00:54:43] [Craft Async Scheduler Management Thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[00:54:43] [Craft Scheduler Thread - 5034/WARN]: [Magic] Plugin Magic v8.7.1-813d9fc generated an exception while executing task 4795765
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.lang.Thread.start0(Native Method) ~[?:?]
	at java.lang.Thread.start(Thread.java:803) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:937) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1343) ~[?:?]
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:687) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncScheduler.cancelTask(CraftAsyncScheduler.java:56) ~[patched_1.16.5.jar:git-Paper-637]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.cancelTask(CraftScheduler.java:263) ~[patched_1.16.5.jar:git-Paper-637]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.cancel(CraftTask.java:142) ~[patched_1.16.5.jar:git-Paper-637]
	at com.elmakers.mine.bukkit.slikey.effectlib.EffectManager.removeEffect(EffectManager.java:282) ~[?:?]
	at com.elmakers.mine.bukkit.slikey.effectlib.EffectManager.done(EffectManager.java:274) ~[?:?]
	at com.elmakers.mine.bukkit.slikey.effectlib.Effect.done(Effect.java:461) ~[?:?]
	at com.elmakers.mine.bukkit.slikey.effectlib.Effect.run(Effect.java:287) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-637]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-637]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-637]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by NathanWolf** [comment]
Do you have all 24GB dedicated to your spigot server? What is your startup command?

Something like `java -Xms10G -Xmx10G` ?

I don't think I've ever had an OOM report before, so I'm guessing something odd is going on here but I can't think of what.

It also seems odd that Spigot *creates* a thread to *cancel* a task .. but I don't really know how the internals work so maybe that's normal.

**Comment by Poulpinounette** [comment]
work by change Xms args. Thank for your amazing support.
