### ISSUE TITLE
leather_horse_armor Conflict with other Plugin material packs

### ISSUE THREAD

**Issue by tang-guo-guo** [elBukkit/MagicPlugin#985]
The Model-Engine plugin requires the use of the leather_horse_armor material
But the automatic download of the material package will overwrite the leather_horse_armor and make the Model-Engine plugin unusable.

**Comment by NathanWolf** [comment]
Try `/mhelp modelengine` or ask this on Discord, the bot has answers. You need to merge the RPs, there are detailed instructions.

**Comment by tang-guo-guo** [comment]
There will be no spell list on the experience bar when you use the material pack on your own after not using the automatic download

**Comment by NathanWolf** [comment]
Use `/getrp download` or follow the instructions to merge and then host your own RP.

**Comment by tang-guo-guo** [comment]
Error using /getrp download command
[00:13:38] [Server thread/INFO]: tang_guo issued server command: /getrp download
[00:13:38] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'getrp' in plugin Magic v10.1.1-addec75
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Airplane-55]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Airplane-55]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2330) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2141) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2122) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[app:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1438) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1416) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1409) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1387) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1298) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Airplane-55]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
	at java.lang.String.replace(String.java:2159) ~[?:?]
	at com.elmakers.mine.bukkit.magic.command.RPCommandExecutor.onCommand(RPCommandExecutor.java:69) ~[[魔法]Magic-10.1.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Airplane-55]
	... 21 more

**Comment by NathanWolf** [comment]
What does `/version magic` say?

**Comment by tang-guo-guo** [comment]
![2021-11-05_00 17 53](https://user-images.githubusercontent.com/71223830/140377807-8d6a51ae-cce1-4f46-ae81-823b577b8857.png)

**Comment by NathanWolf** [comment]
Thanks- there is a bug there, I guess you have turned off the RP?

For now you have three options:

1. Follow the instructions to merge your RP with the Magic RP, host it and set Magic to give you that RP
2. Leave the magic config alone, all of your players have to use `/getrp download` which will make the plugin skip sending them the RP
3. Wait for a fix

**Comment by NathanWolf** [comment]
I fixed the error you got and made it so `/getrp download` can work even with the RP disabled. 

I've also added a new option for config.yml, `assume_resource_pack_downloaded: true`

If you want the changes, you can get the dev build from here:
https://jenkins.elmakers.com/job/MagicPlugin/4058/artifact/Magic/target/Magic-10.2-SNAPSHOT.jar
